let señor_de_los_anillos_libro = {
    nombre: 'El Señor de los Anillos',
    nombre_objeto: 'señor_de_los_anillos_libro',
    introducción: "El Señor de los Anillos (The Lord of the Rings en el original inglés) es una novela escrita por J.R.R. Tolkien entre 1937 y 1949. Fue realizada como secuela debido al éxito de su anterior libro, El Hobbit, en el que apareció por primera vez la mítica Tierra Media y los hobbits. A causa de su longitud respecto la obra anterior, Tolkien decidió divididirla en seis libros, pero la idea no acabó de convencer a la editorial, y finalmente fue convertida en una trilogía, cuyos títulos fueron El Señor de los Anillos: La Comunidad del Anillo, El Señor de los Anillos: Las Dos Torres y El Señor de los Anillos: El Retorno del Rey. Todas fueron finalmente publicadas entre 1954 y 1955."+
    "<br>El argumento de El Señor de los Anillos tiene lugar alrededor de sesenta años después del viaje del hobbit Bilbo Bolsón a Erebor, en la celebración de su centesimodecimoprimer cumpleaños. Bilbo deja el misterioso anillo mágico que encontró en su viaje a su sobrino Frodo con toda su herencia a petición de Gandalf, que también pide a Frodo que procure no usar mucho el anillo, ya que el comportamiento que Bilbo ha tenido últimamente le preocupa. Eventualmente, las sospechas de Gandalf se ven confirmadas, y el anillo es nada más y nada menos que el Anillo Único forjado por Sauron el Señor Oscuro, que ha vuelto con fuerzas renovadas y busca su preciado objeto. De este modo, Frodo y sus amigos se ven involucrados en unos grandes acontecimientos y aventuras que culminarán con la Guerra del Anillo y el Fin de la Tercera Edad."+
    '<br>Tras su publicación, el Señor de los Anillos ha sido leído por miles de lectores de todo el mundo y se ha convertido en un clásico del género fantástico, inspirando gran cantidad de obras de fantasía posteriores. Ha sido adaptada además en todo tipo de medios, destacando sobre todo la trilogía cinematográfica dirigida por Peter Jackson entre 2001 y 2003.',
    cards: [
        {
            nombre_objeto: 'señor_de_los_anillos_la_comunidad_del_anillo_libro',
            titulo: 'El Señor de los Anillos: La Comunidad del Anillo',
            image: 'images/libros/esdla_comunidad_del_anillo.jpg',
            tipo: 8
        },
        {
            nombre_objeto: 'señor_de_los_anillos_las_dos_torres_libro',
            titulo: 'El Señor de los Anillos: Las Dos Torres',
            image: 'images/libros/esdla_las_dos_torres.jpg',
            tipo: 8
        },
        {
            nombre_objeto: 'señor_de_los_anillos_el_retorno_del_rey_libro',
            titulo: 'El Señor de los Anillos: El Retorno del Rey',
            image: 'images/libros/esdla_el_retorno_del_rey.jpg',
            tipo: 8
        }
    ],

}  

let señor_de_los_anillos_la_comunidad_del_anillo_libro = {
    nombre: 'El Señor de los Anillos: La Comunidad del Anillo',
    ficha: {
        'Autor': 'J. R. R. Tolkien',
        'Año de publicación': '29/7/1954',
        'Número de páginas': '568',
        'Género literario': 'Novela',
        'Subgénero': 'Fantasía heroica',
        'Legendarium': 'Sí',
        'Título original': 'The Lord of the Rings: The Fellowship of the Ring',
    },
    image: 'images/libros/esdla_comunidad_del_anillo.jpg',
    indice:['Prólogo','Libro I: El Primer Viaje / El Anillo Se Establece','Libro II: El Viaje de los Nueve Compañeros / El Anillo va al Sur'],
    introducción: ['El Señor de los Anillos: La Comunidad del Anillo, es el primero de tres volúmenes de la saga del género épico fantástico El Señor de los Anillos. Se divide en dos libros, Libro I y II. Fue publicada el 29 de Julio de 1954 en el Reino Unido por Allen y Unwin.'],
    información: {
        'Prólogo': [
            'El libro comienza con un prólogo, que resume los eventos del primer libro, El Hobbit. Relata la historia del anillo y de su creador Sauron, y de Smeagol y su amigo Deagol, y de cómo llega el anillo a ellos tras la reciente "derrota" de Sauron. También explica cómo Bilbo Bolsón encuentra el "Anillo Único", después de que Smeagol que ahora es Gollum, lo pierde. Entonces Bilbo vuelve a Bolsón Cerrado en La Comarca y la historia de Frodo Bolsón, sobrino de Bilbo, comienza.',
            'También habla de historias como el arte de la hierba para pipa, un habito de los hobbits; del orden geográfico en el que se encuentra La Comarca de las cuatro cuadernas; y de algunos otros apuntes referentes a los hobbits como su historia, costumbres y cultura.'
        ],
        'Libro I: El Primer Viaje / El Anillo Se Establece': [
            'El primero establece el escenario para la aventura, y sigue a Frodo Bolsón mientras huye de su hogar en La Comarca, para escapar de los esbirros del "Señor Oscuro". Sauron busca el Anillo Único que le permitirá controlar a los portadores de los otros diecinueve Anillos y controlar las tres principales razas de la Tierra Media: Elfos, Hombres y Enanos. El Anillo Único ha sido heredado por Frodo, el cual se encuentra, sin querer, en medio de una lucha por la dominación del mundo.',
            'Bilbo Bolsón y Gandalf el Gris deciden heredarle a Frodo (el hijo adoptivo de Bilbo, nieto y su única compañía) el Anillo pues saben que el peligro se acerca con el Anillo cerca de La Comarca y por consejo de Gandalf, Frodo va con Sam aunque inesperadamente tambien van Merry y Pippin a acompañarle.',
            'Luego narra las aventuras que tienen que transcurrir Frodo con sus amigos Merry, Sam, y Pippin; las aventuras que tuvieron con Tom Bombadil y su amada esposa Baya de Oro (ambos de raza desconocida) que viven en el Bosque Viejo, perseguidos siempre por los nueve, llamados Jinetes Negros, sirvientes del Señor Oscuro; hasta llegar a Rivendel donde conocen la verdad del anillo, y su peligro para toda la Tierra Media si Sauron lo encuentra.',
            'El primer capítulo en el libro comienza bastante a la ligera, como continuación de el Hobbit, que es más un cuento',
            '<h2>El Regreso de la Sombra </h2>',
            'Tras una gran fiesta que causa gran revuelo en la Comarca, Frodo Bolsón, sobrino de Bilbo, recibe como parte de la herencia de su tío el misterioso anillo que Bilbo encontró en su viaje sesenta años antrás. Sin embargo, Gandalf el Mago, amigo suyo y de Bilbo, le recomienda no usarlo porque no le gusta el comportamiento que tuvo Bilbo antes de renunciar al anillo.',
            'Después de veinte años de idas y venidas, Gandalf confirma a Frodo sus temores: el anillo de Bilbo y que antes era de Gollum es nada más y nada menos que el mismísimo Anillo Único, que le fue arrebatado por Isildur a Sauron, el Señor Oscuro, en la tierra de Mordor en tiempos inmemoriales. Ahora Sauron ha vuelto con fuerzas renovadas, y busca con insitencia su anillo perdido. El único modo de impedir que Sauron se apodere de él y domine la Tierra Media es viajar a Mordor y arrojarlo al cráter del Orodruin, el Monte del Destino, el volcán en el que Sauron lo forjó y el único cuyos fuegos pueden destruir el objeto.',
            'Como Gandalf ve que esta tarea es demasiado grande para Frodo, le recomienda que viaje sólo hasta Rivendel con amigos de confianza, y allí tendrá lugar un Concilio en el que se decidirá que hacer con el Anillo Único. Antes de irse, Gandalf le dice a Frodo que cuando llegue el día de la partida, si él no ha regresado, que parta inmediatamente, asegurándole que se reunirán en la aldea de Bree.',
            '<h2>Aventuras de cuatro hobbits </h2>',
            'Llega el día de la partida y Gandalf no aparece, de modo que Frodo parte con sus amigos Sam y Pippin hacia Los Gamos (después de vender Bolsón Cerrado a los Sacovilla-Bolsón) con el precepto de que se muda a la tierra de su infancia. Por el camino se cruzan con unos misteriosos Jinetes Negros que no gustan nada a Frodo, de modo que en su trayecto procuran esconderse de ellos. Una vez llegan a Cricava, en los Gamos, los tres hobbits se reúnen con Gordo Bolger y Merry, decidiendo que Bolger se quedará cuidando de Cricava y Frodo, Sam, Pippin y Merry irán con Frodo a Rivendel.',
            'Para evitar a los Jinetes Negros, Frodo y compañía deciden en intentar llegar a Bree cruzando el Bosque Viejo. Sin embargo, este atajo resulta desastroso, y los cuatro hobbits casi se ahogan por acción del Hombre-Sauce (el árbol más malvado del bosque) de no ser porque aparece Tom Bombadil, el amo del bosque, que salva a los hobbits de las ramas del sauce. Tom los invita a reposar en su casa junto con Baya de Oro y también los salva de caer en la maldición de un tumulario durante la travesía de las tétricas Quebradas de los Túmulos. Al llegar finalmente al camino de Bree, Tom se despide de ellos y les desea buena suerte en su viaje.',
            '<h2>Trancos y la huida hacia Rivende </h2>',
            'Al llegar a Bree, Frodo, Sam, Pippin y Merry se alojan en el Poney Pisador, una animada posada que les fue recomendada por Gandalf y por Bombadil. Allí conocen a Trancos, un misterioso hombre montaraz que dice conocer a Gandalf. Su amistad es confirmada cuando Frodo recibe una carta de Gandalf a manos del despistado Cebadilla Mantecona, el propietario de la posada. En ella le cuenta Frodo que el verdadero nombre de Trancos es Aragorn y que tardará más de lo previsto en reunirse con él. Los cuatro hobbits deciden finalmente confiar en Trancos gracias a su consejos para evitar los Nazgûl (los Jinetes Negros), quedando en viajar a Rivendel con su compañía.',
            'Desde Bree, los hobbits y Trancos se dirigen hacia el este evitando todo lo posible el Gran Camino Oeste para evitar a los Jinetes Negros. Tras varios días, llegan aAmon Sûl, donde encuentran lo que parece ser una señal de Gandalf indicando su paso por el lugar. Esa misma noche, sin embargo, son atacados por cinco de los Nazgûl. El ataque es neutralizado por la ayuda de Trancos, que utiliza el fuego, pero Frodo queda gravemente herido por un puñal que le clavó uno de los jinetes. ',
            'Tras la herida de Frodo, el grupo avanza más lentamente, pero logran llegar al Bosque de los Trolls a pesar de la agonía de Frodo, que los obliga a ir por el camino. Afortunadamente, en el camino se encuentran con Glorfindel, un elfo de Rivendel enviado por Elrond a buscarles. Ya muy cerca del valle de Rivendel, en el Vado del Bruinen; Trancos, Glorfindel y los hobbits son de nuevo atacados por los Nazgûl, esta vez por todos los Nueve. Glorfindel deja a Frodo huir en su caballo debido a que lo quieren a él y al Anillo. La ferocidad de la persecución, el Anillo y la maldad de la herida hacen que Frodo se desmaye mientras huye en caballo. Lo último que ve es como una inmensa ola del río se lleva a los Jinetes Negros y a sus oscuros caballos.'
        ],
        'Libro II: El Viaje de los Nueve Compañeros / El Anillo va al Sur':[
            'El libro II narra la estancia de Frodo en Rivendel, donde se está organizando un plan para destruir el Anillo en Mordor. Al principio, Frodo se encuentra con su tío Bilbo, al que lleva sin ver desde que éste se fuera de Hobbiton mucho antes. Frodo sale de Rivendel con nueve compañeros de viaje: dos hombres, Aragorn, hijo de Arathorn y desdendiente de Isildur; y Boromir, hijo del Senescal de la tierra de Gondor; Legolas un príncipe elfo del Bosque Negro del norte; Gandalf el viejo amigo de Frodo y poderoso mago; Gimli el Enano; y sus tres compañeros hobbits.',
            'Estos nueve acompañantes son elegidos para representar las razas libres de la Tierra Media, y para contrarrestar a los Nueve Jinetes. También salen acompañados por Bill, el pony que Trancos y los hobbits habían comprado a Bill Helechal en Bree como una mula de carga. Su intento de cruzar las Montañas Nubladas es frustrado por las fuertes nevadas que tapan el camino, por lo que se ven obligados a tomar un camino por debajo de las montañas, a través de Moria, un antiguo reino enano, ahora custodiado por orcos y otras criaturas malignas y vigilado en su puerta occidental por el Guardián del Agua.',
            'Justo antes de escapar de Moria, Gandalf cae en el abismo, mientras combate un Balrog. Los restantes ocho miembros de la Comunidad, pasan algún tiempo en el Bosque de Lothlórien, donde reciben regalos de la reina elfa Galadriel, que en muchos casos, serán útiles más adelante. Dejan Lórien por el río, pero Frodo comienza a darse cuenta de que el Anillo está teniendo un efecto malévolo en algunos miembros de la Comunidad, especialmente en Boromir, que trata de tomar el Anillo de Frodo. En esto, Frodo se pone el anillo para escapar de él. Más tarde, Boromir es atacado por los orcos, al intentar defender a Merry y a Pippin.',
            'Este libro termina, cuando Frodo y Sam parten en secreto para Mordor, y la Comunidad del Anillo se disuelve.',
            '<h2>El Concilio de Elrond</h2>',
            'Frodo recobra la conciencia ya en Rivendel, donde es recibido por sus amigos y, al fin, por Gandalf. Frodo tiene muchas preguntas que hacer, pero el mago le pide que espere y que disfrute de la Casa de Elrond, todo se aclarará en un concilio que tendrá lugar la mañana siguiente. Paseando por Rivendel, Frodo encuentra nada más y nada menos que a su tío Bilbo, ya viejo y retirado en Rivendel, escribiendo canciones y muy contento de ver a su sobrino. Se revela también que la ola del Bruinen que se llevó a los Nazgûl fue comandada por Elrond para ayudarlo en su huida.',
            'A la mañana siguiente, en Rivendel se convoca el Concilio de Elrond, en el que acuden miembros importantes de las Razas Libres y en el que se hablan de muchos hechos sobre la historia del anillo y los movimientos de las fuerzas de Sauron. En él, Gandalf relata la mala noticia de que Saruman el Blanco, otrora líder de los Magos, se ha pasado también al Enemigo, teniendo retenido a Gandalf, que sólo pudo escapar con la ayuda de Gwaihir, el Señor de las Águilas, siendo este el motivo de su larga ausencia. Frodo y sus amigos descubren también que Trancos-Aragorn es nada más y nada menos que un descendiente de la Casa de Isildur, y por lo tanto, heredero en pleno derecho al trono del reino dúnedain de Gondor, al sur de la Tierra Media.',
            'Tras mucho deliberar, Elrond acuerda en crear una compañía, formada por representantes de las Razas Libres, que lleve a cabo la gran misión de portar el Anillo Único y a ser posible, destruirlo en las Grietas del Destino. El grupo, llamado la Comunidad del Anillo, se acaba conformando de Nueve Caminantes: Frodo, el Portador del Anillo; sus amigos hobbits Sam, Pippin y Merry; Gandalf el Mago, Aragorn; Legolas, elfo hijo del rey Thranduil del Bosque Negro; Gimli el Enano, hijo de Glóin, que acompañó a Bilbo en la Reconquista de Erebor; y Boromir, un valiente hombre de Gondor hijo mayor de Denethor, el senescal del reino.',
            '<h2>El Viaje de la Comunidad</h2>',
            'Tras varios preparativos, la Comunidad parte en su viaje el 25 de diciembre con la bendición de Elrond. Durante muchos días, el grupo avanza hacia el sur paralelo a las Montañas Nubladas hasta llegar a Acebeda, donde descubren que bandadas de crebain espías de Saruman peinan la región. La Compañía entonces intenta cruzar las montañas por el paso de Caradhras. Sin embargo, una incesante tormenta de nieve impide la travesía del paso y el grupo debe replantearse qué rumbo seguir.',
            'Boromir propone cruzar las montañas por elPaso de Rohan o rodearlas e ir por la costa, pero la presencia de las tropas de Saruman no deja perspectivas muy alentadoras. Gandalf propone intentar atravesar las Minas de Moria, una inmensa mina de Enanos ahora abandonada que discurre por las raíces del pico Caradhras. A pesar del tétrico nombre de Moria, la Compañía acuerda en cruzarlas. Tras un día de viaje, la compañía entra en las minas por las Puertas del Oeste, aunque han sido encerrados por una criatura maligna que montaba guardia en el lago de la entrada.',
            'A pesar del incidente, las primeras etapas del cruce de las minas son tranquilas y sin contrantiempos, y Gandalf, que ya había estado antes en las minas, logra orientarse suficietemente en el laberinto de las minas. Sin embargo, Frodo empieza a oír pasos muy lejanos que persiguen a la Comunidad, pero no sabe decir si son imaginaciones suyas o los oye de verdad. Al tercer día de viaje, poco después de descubrir tristemente la tumba del enanoBalin, que había intentado recuperar Moria, la Comunidad es atacada por un grupo de Orcos y Trolls comandados por nada más y nada menos que un Balrog, el mismo que fue despertado por los Enanos por su excavación y el mismo que acabó con el rico reino que llegó a ser Moria.',
            'Gandalf se enfrenta cara a cara con el Balrog en el Puente de Khazad-dum muy cerca de la salida de las minas, y logra arrojarlo al abismo, pero el látigo infernal del Balrog arrastra también al viejo mago, que insta a la compañía que huya cuanto antes. Los miembros de la compañía logran salir de las Minas y muy apenados, lloran por Gandalf y lo dan por muerto.',
            'La Compañía, partiendo de las Puertas del Este de Moria y atravesando el Valle del Arroyo Sombrío, llega a los bosques de árboles dorados de Lothlórien. Allí son acogidos en Caras Galadhon, capital del bosque, por Celeborn y Galadriel, y reposan allí durante tres semanas. Durante el tiempo de descanso, Gimli y Legolas se hacen amigos, Galadriel invita a Frodo y a Sam a ver su espejo mágico y Boromir empieza a notarse preocupado. Finalmente, la compañía parte por el río Anduin con varios obsequios de Galadriel y sobre unos botes élficos de parte de los elfos de Lothlórien.',
            '<h2>La Disolución de la Compañía</h2>',
            'Desde ese punto, la Compañía viaja curso abajo del Anduin, navegando en botes. Durante la travesía Frodo, Aragorn y Sam notan que algo les sigue y deducen que se trata de Gollum, que debió llevar siguiéndoles desde Moria, donde debía estar escondido. Ya cerca de Emyn Muil, sufren un leve ataque por una incursión de Orcos comandados por lo que parece ser un Nazgûl alado.',
            'La Comunidad pasa los pilares de Argonath y llega a Nen Hithoel desembarcando en Parth Galen tras diez días de navegación desde Lothórien. En Parth Galen, ya cerca de Mordor, los miembros de la Comunidad discuten qué camino deben seguir, si deben ir a Minas Tirith, en Gondor; o ir directamente al País de la Sombra. Finalmente, acuerdan que lo debe decidir el Portador del Anillo, de modo que dejan a Frodo un par de horas para que lo reflexione. Frodo se aleja del grupo y se sienta en un claro para pensar. No pasa mucho tiempo cuando Boromir se le acerca y le aconseja entregar el Anillo al reino de Gondor para utilizarlo contra Sauron, pero como Frodo se niega, Boromir monta en cólera y se dispone a atacar a Frodo, momento en el que éste se pone el anillo y escapa invisible. Boromir tropieza y queda tendido, cosa que le hace recobrar el sentido y darse cuenta de lo que ha hecho. Arrepentido, llama a Frodo en vano.',
            'Mientras, los otros miembros detectan la ausencia de Frodo y se dividen para buscarlo, pero en ese momento, un grupo de Orcos Uruk-hai comandados por Lurtz ataca a la Comunidad. Tras una dura lucha, Aragorn, Gimli y Legolas encuentran a Boromir atravesado por flechas, que había intentado defender a Pippin y a Merry pero los Orcos habían logrado secuestrarlos. Antes de morir, Boromir confiesa que intentó arrebatarle el Anillo a Frodo por la fuerza, pero Aragorn lo perdona y lo acuna antes de fallecer.',
            'El único miembro que no se encuentra con los demás es Sam, que estaba buscando por la ribera del lago y vió que uno de los botes se iba solo. Sam, comprendiendo que Frodo intenta irse, va directo a él, pero al no saber nadar se hunde. Finalmente, Frodo lo rescata, y medio enfadado medio contento, le permite ir con él a Mordor. De este modo, los dos hobbits llegan a la otra orilla del Anduin y se adentran en Emyn Muil.'
        ]
    },
}

let señor_de_los_anillos_las_dos_torres_libro = {
    nombre: 'El Señor de los Anillos: Las Dos Torres',
    ficha: {
        'Autor': 'J. R. R. Tolkien',
        'Año de publicación': '11/11/1954',
        'Número de páginas': '462',
        'Género literario': 'Novela',
        'Subgénero': 'Fantasía heroica',
        'Legendarium': 'Sí',
        'Título original': 'The Lord of the Rings: The Two Towers',
    },
    image: 'img/libros/el_señor_de_los_anillos_las_dos_torres.jpg',
    indice: ['Libro III: La traición de Isengard', 'Libro IV: El Anillo viaja al Este'],
    introducción: [
        'El Señor de los Anillos: Las Dos Torres, es la segunda parte de la Trilogía de El Señor de los Anillos de J.R.R. Tolkien. En ella se narra el ataque de Saruman sobre Rohan, y la posterior caída del mago y destrucción de su fortaleza, Isengard. También cuenta como Gollum guía a Frodo y Sam para llegar hasta Mordor. Es el segundo libro más largo de la Trilogía, siendo el más largo El Señor de los Anillos: La Comunidad del Anillo.'
    ],
    información: {
        'Libro III: La traición de Isengard': [
            '<h2> Persecución en Fangorn </h2>',
            'Aragorn, Gimli y Legolas tienden al cuerpo fenecido de Boromir sobre un bote y lo dejan navegar corriente abajo por el Rauros para que descanse en paz. Seguidamente, tras reflexionar, toman la decisión de seguir la pista de los hobbits Pippin y Merry secuestrados por los orcos, ya que intuyen que Sam y Frodo quieren hacer su camino a Mordor en solitario.',
            'Mientras tanto, Pippin y Merry son obligados a avanzar pesadamente a través de las llanuras de Rohan, suplicio durante el cual se dan cuenta que sus captores son orcos a las órdenes de Saruman. Ya cerca del bosque de Fangorn, un grupo de hombres montados a caballo ataca al grupo de orcos, momento en el que los hobbits aprovechan para escapar al bosque. Una vez dentro, se encuentran con Bárbol, un viejo ent que después de comprobar que no son orcos, acoge a Pippin y a Merry. Las historias que estos cuentan conmueven a Bárbol, que no es otro que el señor de Fangorn, y decide convocar a todos los ents del bosque para celebrar una asamblea. Tras mucho discutir, los ents deciden que ya no soportan más los daños que Saruman inflige a la naturaleza y que procederán a atacarIsengard.',
            'Aragorn, Gimli y Legolas siguen el rastro de los orcos secuestradores a través de las llanuras lo más rápido que pueden y al tercer día se encuentran con un grupo de jinetes comandados por Éomer, el sobrino de Théoden Rey de Rohan. Los tres viajeros piden a los jinetes si en el grupo de orcos que atacaron encontraron a los hobbits, pero ante la negativa de los soldados, Aragorn, Gimli y Legolas continúan buscando hasta Fangorn.',
            'Al día siguiente, el trío se adentra en el bosque de Fangorn y sube a una colina para ver el alrededor, cuando tienen un encuentro inesperado. El mismísimo Gandalf sale a su encuentro desde el bosque, pero ahora vestido de blanco. Algo afligido pero con aparentes nuevas fuerzas, les cuenta que consiguió derrotar al Balrog en la cima del pico Cuerno de Plata, pero que murió de cansancio. Sin embargo, fue traído de nuevo al mundo (se sospecha que por orden de los Valar) vestido de blanco, convirtiéndose en el nuevo jefe de los Magos. Gwaihir lo rescató de la cima y lo llevó a Lothlórien, y desde allí se encaminó a Fangorn buscándolos. Por último, les cuenta que no se preocupen por Pippin y por Merry, ya que están a buen recaudo con Bárbol; y les insta a partir inmediatamente hacia Edoras, la capital de Rohan, ya que Saruman está planeando atacar y acabar con el reino de una vez por todas.',
            '<h2> Isengard contra Rohan </h2>',
            'Tras cabalgar toda la noche, los cuatro llegan a Edoras al amanecer, entrando en Meduseld  y encontrándose al rey Théoden prematuramente envejecido y enfermo. Gríma "Lengua de Serpiente", su consejero, lo ha estado corrompiendo con sus palabras viperinas, pero Gandalf revela que trabaja para Saruman y cura a Théoden, que expulsa a Gríma inmediatamente. Ya más alegre por su renacer, el rey de Rohan sigue los consejos de Ganalf y organiza un ejército para partir hacia la fortaleza de Cuernavilla, en el Abismo de Helm; que es el próximo objetivo de Saruman. Gandalf, Aragorn, Legolas y Gimli también se suman para luchar contra las tropas de Saruman.',
            'Antes de llegar al Abismo de Helm, Gandalf se aleja hacia Isengard sin dejar razones claras. La avanzadilla del rey llega a Cuernavilla poco antes de la llegada del ejército de Saruman, formado por orcos, semiorcos y hombres de las Tierras Brunas. Durante toda la noche, tiene lugar una épica defensa del Abismo en la que Aragorn, Legolas y Gimli llevan a cabo un importante papel. Con el amanecer llega la victoria, pero con ella también un extraño bosque que se planta en la entrada del Abismo, en el que los orcos supervivientes se esconden. Gandalf vuelve por la mañana y cuenta que el bosque es un rebaño de Ucornos vigilado por ents, seres legendarios en los que los Rohirrim ya no creían. El mago también propone al rey Théoden y a Aragorn, Legolas y Gimli que lo acompañen con algunos hombres a Isengard.',
            '<h2>Saruman en Orthanc y diversos reencuentros</h2>',
            'El grupo parte ese mismo día y llega al Valle del Mago al día siguiente. Allí, con sorpresa, se encuentran que Isengard ha sido inundada, quedando sólo la torre de Orthanc intacta. Gandalf y Bárbol, que se encuentra allí les cuenta que todo ha sido obra de los ents de Fangorn, y que Saruman se encuentra escondido en Orthanc con Gríma. Pero la mayor sorpresa para Legolas, Gimli y Aragorn es que encuentran a los hobbits Pippin y Merry allí, que les cuentan todo lo ocurrido con acompañamiento de hierba para pipa.',
            'Esa misma noche, el grupo de los hombres de Théoden, Gandalf, Aragorn, Gimli, Legolas, Pippin y Merry acampa en Dol Baran, pero Pippin no puede dormir debido a que siente mucha curiosidad por examinar la piedra recogida por Gandalf. Pippin la hurta mientras el mago duerme, pero al mirarla ve a nada más y nada menos que a Sauron, que se burla de él pensando que es el hobbit que portaba el anillo, que ha sido capturado por Saruman. Pippin grita y despierta al campamento. Gandalf, al ver lo que le ha pasado a Pippin, decide llevárselo a Minas Tirith para alejarlo del enemigo, ya que prevé que en breve Sauron enviará algún Nazgûl alado para comprobar si han capturado al hobbit portador del Anillo Único. Antes de dormirse Pippin, Gandalf le cuenta que la piedra que ha observado es una palantír, unas esferas que usaban los reyes dúnedain para comunicarse y que ahora deben haber caído en manos del Enemigo. Gandalf se despide apresuradamente del grupo y monta con Pippin sobre Sombragrís en dirección al este, hacia Minas Tirith, en el reino de Gondor.'
        ],
        'Libro IV: El Anillo viaja al Este':[
            '<h2>Rumbo a Mordor con ayuda de Sméagol</h2>',
            'Tres días después de haberse separado de la Comunidad, Sam y Frodo se encuentran totalmente desorientados en el laberinto de colinas de Emyn Muil. Durante tres jornadas han intentado bajar de la cordillera por el este sin resultado, pero al fin encuentran una profunda garganta que parece conducir a las tierras bajas. Sin embargo, durante el descenso se encuentran con alguien inesperado: Gollum les ha estado siguiendo y cae ahora sobre ellos. Sin embargo, Sam y Frodo, armados con dagas logran retenerlo. Gollum se queja con lloriqueos e intenta que le liberen diciéndoles que les hará de guía para ir a Mordor, puesto que en un tiempo lo retuvieron allí y tuvo que escapar. Frodo apoya este alegato y como agradecimiento, llama a Gollum por el nombre de Sméagol, que era el que tenía cuando Gollum era un hobbit y no había encontrado el Anillo. Sméagol cambia de personalidad y se muestra mucho más agradable con Frodo y Sam, aunque este último no se fía del todo.',
            'Sméagol guía a los hobbits a través de una garganta oculta y descienden hasta las Ciénagas de los Muertos. Procuran viajar sobre todo de noche para cruzarlas, algo peligroso ya que en las Ciénagas son acosados por los fuegos fatuos de los Muertos. Sméagol aconseja a los hobbits que no se queden mirándolos y finalmente, al cabo de unos días, llegan a los pies de las Ered Lithui, montañas que bordean el norte de Mordor.',
            'En el día siguiente llegan ya a las Puertas de Mordor, y se esconden en un hueco pedregoso del terreno para vigilar. Ven que muchas tropas de Hombres malvados provenientes de Rhûn y de Harad entran enMorannon, la Puerta Negra; pero deciden claramente que es imposible entar a Mordor por allí, ya que la entrada se encuentra completamente vigilada. Sméagol les dice entonces que existe otro camino para entrar a Mordor, el que utilizó él para huir del País Oscuro; y que para encontrarlo deben ir al sur por las tierras de la ribera oriental del Anduin. Frodo, y Sam (aunque a regañadientes) aceptan la proposición de Sméagol y siguen el camino que se dirige al sur desde Morannon.',
            '<h2> Los hombres de Faramir</h2>',
            'El viaje a partir de allí es mucho más agradable, y aunque Ithilien, la región que cruzan los hobbits y Sméagol, se encuentra bajo poder de Mordor, aún sigue siendo un lugar frondoso y lleno de plantas. Un par de días más tarde, los hobbits deciden tomarse un día de descanso. Sam pide a Sméagol que vaya a cazar algunos conejos para hacer algún guisado mientras Frodo duerme. Pero mientras tanto Sméagol está ausente, un grupo de Hombres parecidos a Montaraces debido a que han visto el humo del guiso, pensando que los hobbits son centinelas de Mordor.',
            'Faramir, el capitán del grupo de hombres ordena a dos de sus compañeros que los vigilen, que ya los interrogará después de destruir la avanzadilla de Haradrim que se acerca desde el sur. En poco tiempo estalla una lucha entre los hombres de Faramir y los hombres de Harad, siendo estos úlimos derrotados. A Sam no le gusta nada ver la batalla de hombres contra hombres, pero logra ver un Olifante que escapa con un sonido atronador, algo que le sorprende pues pensaba que no existían tales criaturas. Tras la batalla, Faramir vuelve con los hobbits e interroga perspicazmente a Frodo, y contándole que su hermano Boromir, el cual formaba parte de su compañía, está muerto. Frodo se sorprende de la noticia, pues huyó antes de la muerte de Boromir, pero sus declaraciones convencen a Faramir de que la muerte de su hermano no fue culpa suya. Por último, nombra a los hobbits amigos de Gondor (pues Faramir es también un amigo de Gandalf), y les invita a pasar la noche con sus hombres en Henneth Annûn, un refugio que su avanzadilla suele utilizar.',
            'Pero mientras duermen en el apacible escondite, los hobbits son despertados de nuevo por Faramir: una criatura a la que los hombres de Gondor habían visto esa mañana con Frodo y Sam está pescando en el estanque de Henneth Annûn. Cualquier desconocido que pise el escondite es castigado con la muerte, pero Faramir no ordena matarlo porque conoce que la criatura está relacionada con los hobbits. Finalmente, Frodo les cuenta que es Sméagol, un guía de su viaje, y ruega que lo capturen sin hacerle daño. Los hombres así lo hacen, pero Sméagol lo interpreta como una traición de Frodo y se muestra mucho más hosco. Al fin, a la mañana siguiente, Faramir les desea suerte en su viaje y les regala algunas provisiones antes de que los hobbits, acompañados de nuevo por Sméagol, de despidan.',
            '<h2> El Valle de Morgul</h2>',
            'A pesar de los últimos sucesos ocurridos, Sméagol decide seguir guiando a los hobbits. Tras un apresurado viaje, los tres viajeros llegan a la Encrucijada y entran al Valle de Morgul, donde según Sméagol hay un camino escalonado poco vigilado que permite el acceso a Mordor. Instantes después de llegar al camino, llamado Escaleras de Cirith Ungol, los hobbits, a hurtadillas, contemplan cómo de la tenebrosa ciudadela de Minas Morgul sale un gran ejército capitaneado por el Capitán de los Nazgûl, algo que les congela de miedo.',
            'Una vez las fuerzas de Mordor se alejan, Frodo, Sam y Sméagol siguen subiendo por el camino lleno de escalones hasta llegar a la entrada de un túnel oscuro y maloliente. Sméagol-Gollum les dice que el camino sigue por ahí, sin decirles el nombre de la cueva: Torech Ungol, el Antro de Ella-Laraña. Los hobbits avanzan en lo que parece ser una eternidad por el túnel y de pronto descubren que Sméagol ha desaparecido. Poco después llegan a la salida, encontrándola cubierta de gruesas telarañas, pero Frodo y Sam logran romperlas con sus espadas. Frodo, envalentonado por el éxito del viaje, avanza hacia el paso hacia Mordor, y Sam intenta advertirle de que la torre que hay en el paso parece ocupada cuando Gollum sale tras él y lo ataca.',
            'Mientras Sam forcejea con Gollum, un monstruo similar a una araña gigante, Ella-Laraña, va directo a Frodo. El peligro hace a Sam más fuerte y lanza Gollum a un lado, que huye despavorido. Seguidamente, se lanza contra Ella-Laraña, a la que clava profundamente su daga, y encuentra a Frodo moribundo por el veneno de la araña. Muy triste, Sam cree que su amo ha fallecido y decide encargarse él mismo de portar el Anillo, guardándoselo. En ese momento, un grupo de orcos sale de la torre del paso (Cirith Ungol) , y se llevan al cuerpo de Frodo mientras Sam se hace invisible con el anillo para esconderse. Escuchando a los orcos, descubre que Frodo no está muerto, sino que está sedado por el veneno de Ella-Laraña, y que deben registrarlo por órdenes del Señor de Mordor. Sam decide entonces ir a salvar a Frodo, aunque no sabe cómo.'
        ]
    },
}

let señor_de_los_anillos_el_retorno_del_rey_libro = {
    nombre: 'El Señor de los Anillos: El Retorno del Rey',
    ficha: {
        'Autor': 'J. R. R. Tolkien',
        'Año de publicación': '1955',
        'Número de páginas': '416',
        'Género literario': 'Novela',
        'Subgénero': 'Fantasía heroica',
        'Legendarium': 'Sí',
        'Título original': 'The Lord of the Rings: The Return of the King'
    },
    image: "images/libros/el_señor_de_los_anillos_el_retorno_del_rey.jpg",
    indice: ['Libro V: La Guerra del Anillo', 'Libro VI: El final de la Tercera Edad'],
    introducción: ['El Señor de los Anillos: El Retorno del Rey, es la tercera parte de la Trilogía de El Señor de los Anillos de J.R.R. Tolkien.'],
    información: {
        'Libro V: La Guerra del Anillo': [
            'La historia comienza cuando Gandalf lleva las noticias a Denethor, el Senescal de Gondor, que la guerra es inminente. Gandalf lleva Pippin con él, que entra al servicio de mayordomo. Mientras Aragorn, está destinado para encontrar un ejército perdido de los hombres ya muertos todavía atrapadas en una maldición establecida hace mucho tiempo por su propia desobediencia, en el lugar conocido como el Sendero de los muertos. Los miembros restantes de la Comunidad llevan a las fuerzas de Gondor y Rohan en la defensa de la capital de Gondor, Minas Tirith, lo que resulta en la Batalla de los Campos del Pelennor. La mayoria de los miembros de la compañia que logran sobrevivir a la batalla son dirigidos por Aragorn en un cierto ataque suicida contra las Puertas Negras de Mordor, en parte para distraer a Sauron de la defensa de sus otras fronteras para que Frodo y Sam pueden tener un paso libre hacia Mordor. El ejercito de Aragorn rodea ahora las Puertas Negras de la Morannon e intercambian palabras ociosas con la Boca de Sauron.',
            '<h2>Nubes de guerra</h2>',
            'Tras tres días de cabalgar sin cesar sobre Sombragrís, Gandalf y Pippin llegan a la ciudad de Minas Tirith, capital de Gondor. Allí visitan a Denethor, el Senescal de Gondor, de muy mal humor por ver a Gandalf y sobre todo, por la muerte de su hijo Boromir, de la cual ya se encuentra enterado. Sin embargo, acepta a Pippin como escudero, algo que le divierte un poco. Gracias a ello, Pippin recibe un buen desayuno y conoce a su guía por la ciudad, Beregond, los cuales se hacen amigos rápidamente. Por el atardecer, con Beregond de guardia, Pippin contempla junto con Bergil, hijo de Beregond, la entrada a la ciudad del ejército que debe defenderla de las tropas de Mordor. Proceden de todas partes de Gondor, pero parecen insuficientes. Pippin vuelve a su alojamiento a la ciudad mientras se hace de noche. La mayoría de los ciudadanos no lo notan, pero una nube negra empieza a cubrir el cielo desde el este',
            'En el campamento de Dol Baran, mientras tanto, un grupo de Montaraces del norte capitaneados por Halbarad, Elrohir yElladan alcanzan a la compañía de Théoden, los cuales son recibidos con gran alegría por Aragorn, pues son amigos suyos que vienen a ayudarle en la guerra. Aragorn, como heredero de Isildur y aspirante legítimo al trono de Gondor, se muestra a Sauron por la palantír y decide partir de inmediato hacia Gondor, hacia la guerra. Pero para llegar lo más rápido posible, hay que atravesar los llamados Senderos de los Muertos, un túnel que cruza las Montañas Blancas. Gimli, Legolas y los montaraces del norte lo siguen, a pesar del miedo que les inspira. Théoden y Éomer se despiden de ellos con gran pesar mientras Merry se queda con los hombres de Rohan, a su pesar. Tras un día de marcha, Aragorn y sus compañeros, llamados la Compañía Gris, llegan a Edoras (dondeÉowyn, hermana de Éomer despide tristemente al dúnadan), y suben a El Sagrario, entrando desde allí a los Senderos de los Muertos. Mientras los cruzan con gran temor, un ejército fantasma empieza a seguir a la compañía. Son hombres que fueron maldecidos por Isildur por traicionarle en la guerra, y solo pueden descansar en paz si ayudan de nuevo a uno de sus descendientes. Por este motivo, Aragorn, al salir de los Senderos, convoca a los muertos en la colina de Erech y el ejército fantasma sigue sus órdenes.',
            'Tres días después, Théoden rey de Rohan vuelve a Edoras con un ejército ya ampliado por los hombres de las aldeas recorridas. Merry se ha hecho muy amigo del rey, pero se niega a quedarse en Edoras mientras todo el mundo va a la guerra. El ejército sube al refugio de El Sagrario para deliberar y, al día siguiente, una nube negra cubre el cielo. Hirgon, un mensajero de Gondor cuenta a Théoden que la nube ha estado viniendo desde Mordor, y que Minas Tirith está en peligro crítico. Théoden le tiene mucho aprecio a Merry, pero no le permite ir a la guerra. Sin embargo, a hurtadillas, un soldado de Rohan llamado Dernhelm le ofrece a subirse a la grupa de su caballo, para que así pueda ir también él a la guerra. Mientras tanto, la Tierra Media se oscurece por momentos por la gran nube de Mordor, aunque también por las nubes de guerra.',
            '<h2> El Sitio de Minas Tirith y la Batalla de los Campos del Pelennor</h2>',
            'Las noticias de que un ejército ha salido de Minas Morgul capitaneado por el Rey Brujo llegan a Minas Tirith, algo que ensombrece aún más los días velados por la nube de Mordor. Dos días después vuelve Faramir y sus hombres de Ithilien, pero Denethor se muestra muy duro con su hijo menor Faramir reprochándole su tardanza. Faramir se soprende al ver a Pippin, y cuenta que durante su misión vio a otro par de hobbits, llamados Frodo y Sam. Ante esto, las preocupaciones de Gandalf y Pippin crecen aún más al saber que intentaban entrar en Mordor por el Valle de Morgul. Sin embargo, no hay tiempo para preocuparse, ya que al día siguiente llegan las tropas de Morgul.',
            'La ciudad de Minas Tirith bulle con la actividad de los soldados mientras los enemigos abren una brecha en el Rammas Echor y queman los campos del Pelennor, que quedan a los pies de la capital de Gondor. Faramir vuelve con pocos hombres perseguido por tres Nazgûl alados, pero es salvado por Gandalf. Parece estar terriblemente enfermo, y sólo logra explicar que las tropas de Mordor cruzaron el Anduin en Osgiliath con muchos botes que tenían preparados; los gondorianos no pudieron pararlos. Denethor, al ver al único hijo que le queda así, sube un momento a sus aposentos y baja con una cara demacrada por la desesperación y la pena. Mientras, el ejército enemigo empieza a construir máquinas de asedio, y aunque los hombres de Minas Tirith los atacan continuamente, no logran parar a los orcos que pretenden sitiar la ciudad. Con un ariete llamado Grond, el ejército oscuro empieza a golpear las puertas de la muralla exterior.',
            'Pippin, mientras tanto, intenta consolar a Denethor, pero este lo destituye de su puesto de mayordomo y ordena a sus sirvientes que conduzcan a él y a su hijo Faramir a las criptas de los antiguos reyes, pues tiene la intención de incinerarse, ya que le parece que todo está ya perdido y la ayuda de Rohan no vendrá. Al ver Gandalf que Denethor no puede mandar, decide encargarse él mismo de la comandancia de la defensa de Minas Tirith, algo que rehace los ánimos de los soldados. Sin embargo, en ese mismo momento, Grond echa abajo las Puertas de Minas Tirith y el capitán del ejército de Mordor, el Rey Brujo, entra el primero en la ciudad, cara a cara con Gandalf. Cuando todo parece ya perdido, un sonido de trompetas se oye en la mañana, pues amance: los jinetes de Rohan al fin han llegado.',
            'Théoden y su ejército habían llegado a Minas Tirith sin ser vistos con la ayuda de los hombres de Ghân-buri-Ghân, una tribu del bosque de Drúadan. Los Rohirrim cargan contra el ejército de Mordor y los soldados de Gondor renuevan sus esperanzas. Sin embargo, Théoden es atacado por el mismo rey Brujo, que había vuelto a la batalla. Théoden cae pesadamente bajo Crinblanca, su caballo. Dernhelm, por su parte, defende al rey y desafía al nazgûl, matando a su criatura alada. El Rey Brujo responde con furia, pero lanza de repente un grito al aire; Merry le ha atravesado la rodilla con su daga. Con un horripilante grito, el más poderoso de los nazgûl desaparece para siempre. Con gran tristeza, Merry se despide de Théoden, que lo bendice antes de morir; y encuentra con Éomer a Dernhelm sin yelmo e inconsciente, descubriendo en realidad que era Éowyn disfrazada de soldado, pues deseaba ir a la guerra para defender a su pueblo. Éomer la envía a Minas Tirith con pocas esperanzas, pero en ese momento los hombres de Rohan y Gondor contemplan desesperanzados como una gran flota de corsarios umbarianos remonta el Anduin, creyendo que el resto de Gondor ha caído y que ya no hay esperanza de ganar la guerra.',
            'Éomer se dispone a hacer un último ataque desesperado, cuando se da cuenta que quien dirige a los navíos de Umbar no es otro que Aragorn con el estandarte del Rey de Gondor, acompañado de Gimli y Legolas, los montaraces del norte, y todas las tropas gondorianas de Pelargir, Dol Amroth, Linhir y muchas ciudades más. El ánimo vuelve a renovarse con el feliz reencuentro y finalmente, al atardecer, las tropas de Mordor son aniquiladas y los pocos supervivientes enemigos huyen. En Minas Tirith, todo el mundo, con gran alegría, cuenta que el Rey ha regresado y que va a salvar los reinos de los hombres.',
            '<h2>Reunión antes de la batalla final</h2>',
            'La batalla ha terminado, pero el Enemigo ha hecho un grave daño a Gondor: Denethor acaba suicidánose en una pira, mostrando antes de cometer su muerte que guardaba una palantír, de modo que Sauron le habría hecho ver cosas que lo habrían desesperado y llevarle a la locura. Sin embargo, Gandalf y Pippin logran salvar a Faramir del camino de su padre, donde es trasladado a las Casas de Curación. Allí, Aragorn, gracias a su poder como heredero de Isildur, logra curar a Éowyn, Merry y Faramir, que habían padecido la enfermedad del hálito negro a causa de haberse enfrentado con un nazgûl. Los tres recobran el conocimiento, pero deben quedar en reposo en las Casas. Merry y Pippin se reúnen de nuevo, aunque este último debe ir al ejército de Aragorn como representante de los hobbits.',
            'Los grandes de Gondor y de Rohan se reúnen y deliberan qué deben hacer a continuación. Gandalf advierte de que sólo han logrado una victoria y que la verdadera magnitud de las tropas de Sauron aún están en Mordor. Finalmente, Aragorn, Éomer, Gandalf y el príncipe Imrahil de Dol Amroth coinciden en que deben partir con un ejército a la Puerta Negra para desviar la mirada del Ojo de Sauron y así dejar vía libre a Frodo y a Sam, que deben llegar al Monte del Destino para destruir el Anillo. Gracias al ejército de Rohan y la llegada de otras tropas de Gondor, pueden partir dejando a Minas Tirith mejor defendida que antes, aunque el ejército gondoriano actual queda lejos de lo que era en épocas pasadas.',
            'Tras pocos días, el ejército comandado ahora por Aragorn parte de Minas Tirith y llega a Dagorlad y la Puerta Negra seis días después. Lo encuentran todo en silencio, pero un emisario sale de las almenas, Boca de Sauron, que les ofrece rendirse a cambio de unas condiciones de Sauron. Además, muestra una cota de malla de mithril y unas ropas que pertenecían a Frodo. Boca de Sauron se burla de ellos por "enviar a Mordor un mediano para espiar", pero Gandalf y Aragorn no le creen. Boca de Sauron vuelve adentro las Puertas y un immenso ejército de orcos, trolls y hombres del este y el sur que había estado oculto detrás sale. Aragorn da orden de atacar.'
        ],
        'Libro VI: El final de la Tercera Edad': [
            'Mientras tanto, el valiente y leal Sam (que por un corto tiempo se había convertido en el portador del anillo) imagina el largo sufrimiento de Frodo para recorrer por la tierra estéril de Mordor. Por parte del camino, son capturados por una compañía de orcos y deben fingir ser orcos antes de que puedan escapar. La compañía, cansados y medios vivos, finalmente llegan a la Grieta del Destino, donde el Anillo es destruido junto con Gollum, liberando la Tierra Media del poder de Sauron para siempre. Esto sucede cuando Frodo en el último momento decide quedarse con el anillo en vez de destruirlo, y es atacado por Gollum quien muerde el dedo de Frodo para tomar el anillo, pero este trata de quitarle el anillo, y durante el forcejeo, Gollum cae en la lava, mientras que mantiene el anillo. Frodo y Sam son rescatados por las águilas gigantes quien Gandalf llega montado en uno de ellos al Monte del Destino, de las puertas negras de Morannon.',
            'Aragorn es coronado Rey de Gondor en Minas Tirith. Después de una serie de despedidas, los Hobbits vuelven a casa  sólo para encontrar la Comarca bajo el control de "Zarquino" que descubren que es Saruman, aunque disminuyó en poder, pero no en maldad. Merry y Pippin, ahora experimentados guerreros de Rohan y Gondor, respectivamente, toman la iniciativa, y llevan un levantamiento de los hobbits contra Saruman, liberando la comarca. El tiempo pasa, la Comarca se cura, pero Frodo no. Finalmente Frodo sale hacia las Tierras Imperecederas para encontrar la curación, junto con Bilbo, Gandalf y los elfos. Sam, Merry y Pippin los ven partir y regresan a casa en silencio. Sam es recibido por su esposa Rosita y su hija Elanor.',
            '<h2>En el País de la Sombra</h2>',
            'Sam se arma de coraje y finalmente accede a ponerse el Anillo Único para entrar en la torre de Cirith Ungol y rescatar a Frodo. La suerte juega en parte de Sam, y se encuentra con que una pelea entre los orcos de la fortaleza los ha dejado casi todos muertos. Tras tropezarse con Shagrat, un orco supervivente que huye con un bulto, Sam encuentra finalmente a Frodo en lo alto de Cirith Ungol, despojado de la cota de malla de mithril, cuyo valor seguramente causó la pelea entre orcos. Sam anima a Frodo a seguir, ya que conservan el Anillo, y se con el armamento de los orcos muertos se disfrazan de orcos para intentar pasar desapercibidos. Seguidamente, salen de Cirith Ungol y bajan al Morgai, ya en Mordor.',
            'A partir de allí, el viaje se vuelve cada vez más difícil y penoso, aunque logran sobrevivir gracias a los restos de lembas que les quedan y el agua de pequeños riachuelos raquíticos que cruzan el Morgai. Tras cinco días de marcha, llegan a las cercanías de la Garganta de Hierro, donde son vistos y añadidos a una tropa de orcos, pero logran no ser descubiertos gracias a sus disfraces. Sam y Frodo escapan gracias a un encontronazo con otra compañía de orcos y se esconden en uno de los muchos cráteres del terreno de Mordor. A la mañana siguiente, se encuentran con los alrededores vacíos, y se arriesgan a tomar el camino de Barad-dûr para acercarse al Orodruin y surtirse de las cisternas de agua para tropas que hay en la ruta.',
            'La comida se les acaba, y Frodo cada vez está peor por la carga del Anillo, pareciendo mirar sin ver. Tras una horrible noche en la que reinaba un silencio inquietante, los hobbits llegan finalmente al pie del Monte del Destino. Frodo está tan afectado que Sam debe cargar con él, pero logran subir suficientemente arriba cuando son atacados por Gollum, que había vuelto a seguirles tras su fracaso en Cirith Ungol. Sam repele su ataque, aunque no se da cuenta que en su huida da media vuelta.',
            'Tras un titánico esfuerzo, Sam y Frodo logran llegar a los Sammath Naur y contemplan el cráter de fuego del Orodruin. Sam insta a Frodo a que lanze el Anillo al fuego cuando éste, dominado por el anillo, lo reclama como suyo y se lo pone, volviéndose invisible. En ese momento, aparece Gollum de nuevo, y tras un forcejeo con el Frodo invisible logra apoderarse el Anillo, instante en el que pierde el equilibrio y cae a la lava del volcán. El Anillo Único es destruido, junto con Gollum, en el fuego del Monte del Destino. Frodo vuelve a ser el de antes y abraza Sam, que se alegran de estar juntos en el fin de todas las cosas.',
            '<h2>El Rey retorna</h2>',
            'Momentos antes de la destrucción del Anillo, todo Mordor tiembla con peligro de desmoronarse. El Señor Oscuro nota el estado crítico y manda a los nazgûl, luchando en Dagorlad, que vayan al Orodruin. Sin embargo, antes de llegar éstos, el Monte del Destino estalla en erupción y los nazgûl son consumidos, un terremoto acaba con destruir la Puerta Negra, así como otras fortalezas de Mordor, y finalmente la Torre Oscura misma cae a sus cimientos. Sauron ha sido destruido completamente, y las tropas de orcos y hombres del Enemigo se dispersan en Dagorlad. El ejército de Aragorn ha vencido, y una nueva era comienza. Gandalf, sabiendo que Frodo y Sam han cumplido su misión, envía a Gwaihir Señor de las Águilas y a sus hermanos a buscar a los dos hobbits, aún en el Orodruin.',
            'Sam y Frodo despiertan días más tarde, del todo perplejos, a ver a Gandalf vivo y a todos sus amigos de la Comunidad: Pippin y Merry, Legolas y Gimli, pero se soprenden sobre todo por ver a Aragorn (o Trancos) vestido ya como el rey de Gondor y Arnor. En el Campo de Cormallen, en Ithilien, donde se encuentran, tiene lugar un gran banquete y festejos en honor a los dos hobbits que han destruido al Enemigo. Días más tarde, la comitiva llega a Minas Tirith, donde Éowyn y Faramir se han enamorado y van a casarse.',
            'También llega Elrond desde Rivendel, llevando consigo buenas noticias de la guerra en el norte y también a Arwen, prometida de Aragorn. Aragorn es coronado con grandes honores como el Rey Elessar del Reino Reunido, que reúne de nuevo a Gondor y los antiguos territorios de Arnor dejando a Rohan y la Comarca como estados independientes. Ese mismo día, Aragorn y Arwen contraen matrimonio, y ésta última regala su don de la inmortalidad a Frodo, ya que elige la vida humana para vivir con Aragorn y finalmente morir como la raza de los Hombres.',
            '<h2>Regreso a casa, el Saneamiento de la Comarca y los Puertos Grises </h2>',
            'Semanas más tarde, los miembros de la Comunidad del Anillo parten de nuevo para hacer su último viaje juntos. Los hombres de Rohan los acompañan hasta Edoras, donde tiene lugar el solemne funeral del rey Théoden. En el Paso de Rohan, Aragorn se despide de ellos, y Gimli y Legolas también, pues habían hecho una promesa entre ellos de visitar Fangorn y las Cavernas Centelleantes de Aglarond. Los miembros restantes llegan a Isengard, donde encuentran que Bárbol, ganado por su buen corazón, ha liberado finalmente a Saruman y a Gríma porque no soportaba que estuvieran encerrados tanto tiempo. Aragorn, antes de irse, regala Isengard a los Ents para que lo puedan convertir en su morada.',
            'Tras muchos días bordeando las Montañas Nubladas, el grupo de Elrond y la Comunidad llega por fin a Rivendel. Los hobbits encuentran a Bilbo, ya muy viejo, que se alegra mucho de verles y le gustaría que Frodo escribiera un libro sobre su viaje. Los días pasan rápido en Rivendel, pero finalmente los cuatro hobbits y Gandalf deciden partir para volver a la Comarca. En dos semanas llegan a Bree, donde encuentran, en el Poney Pisador, un Cebadilla Mantecona preocupado porque en Bree ha habido disturbios con hombres del sur y no se oyen noticias de la Comarca. Los hobbits se alarman al oírlo, pero Gandalf, que se despide de ellos por entonces, les dice que con las aventuras que han vivido serán capaces de solucionar cualquier problema que haya en el país de los hobbits.',
            'Al caer la noche del siguiente día, Frodo, Sam, Pippin y Merry son detenidos por un grupo de hobbits frontereros en el Puente del Brandivino y conducidos luego a Hobbiton, donde despistan a sus vigilantes. Desconcertados y por boca del Tío Gamyi y los Coto, descubren que cantidad de Gente Grande se ha instalado en la Comarca y que manda órdenes a los hobbits obedeciendo a un tal "Jefe" en Bolsón Cerrado, supuestamente Lotho Sacovilla-Bolsón. Sin embargo, Frodo, Sam, Pippin y Merry cuentan con experiencia en la guerra y logran emancipar a diversas poblaciones de la zona. Finalmente, muchos hobbits, sacando muchas armas que usaban de decoración, se enfrentan a los hombres invasores en la Batalla de Delagua, único conflicto armado de la Comarca junto con la Batalla de los Campos Verdes. En ella, sale a la luz que Lotho había muerto tiempo atrás y que el verdadero cabecilla de los hombres no es otro que Saruman, conocido como Zarquino por sus esbirros. Saruman se rinde ante los hobbits, no sin antes burlarse de ellos y de Gríma, cosa que produce su muerte por unas flechas hobbits. Así termina la vida del que otrora fue el más grande de los magos.',
            'La Comarca se recupera rápidamente tras la crisis vivida, y varios prisioneros que habían hecho los hombres, como Will Pieblanco, Gordo Bolger o Lobelia Sacovilla-Bolsón son liberados. Gracias a las semillas que le había regalado Galadriel, Sam las esparce por la Comarca y en el año siguiente, 1420, del Cómputo de la Comarca las plantas y bosques florecen como nunca. Frodo recupera Bolsón Cerrado y Sam se traslada allí con su ahora esposa Rosita Coto.',
            'Pero a finales de ese mismo año, Frodo le dice a Sam que venga con él al Bosque Cerrado. Allí se encuentran con Elrond y varios elfos acompañados por Bilbo. Sam comprende que van a partir a los Puertos Grises para no volver a la Tierra Media, y que Frodo va acompañarles porque Arwen le dio su don. A la compañía también se une Gandalf, y Pippin y Merry que quieren despedirse de Frodo. Tras marchar toda la noche hacia el oeste, el grupo llega a los Puertos Grises, al mar. Círdan recibe a los viajeros y antes de embarcar, Frodo, Bilbo y Gandalf se despiden de Sam, Pippin y Merry con gran pesar. El sol se pone cuando el barco parte al océano. Sam, Pippin y Merry regresan a casa sin mirar atrás. Al volver por fin a casa, Sam besa a Rosita y abraza a su pequeña hija Elanor, pronunciando las últimas palabras de la obra: "Bueno, ya estoy de vuelta."'
        ]
    },
}

