let gandalf ={
    nombre: 'Gandalf',
    ficha: {
        'Raza': 'Istari y Maiar',
        'Nacimiento': 'Primera Edad del Sol',
        'Títulos': 'El Gris, El Blanco',
    },
    image: "images/personajes/Gandalf.jpg",
    indice:['Descripción', 'En El Hobbit', 'Guerra del Anillo y regreso a las Tierra Imperecederas', 'En la gran pantalla'],
    introducción:["Gandalf es un personaje de la novela El Señor de los Anillos y El Hobbit , aparece también en el Silmarillion y en el Legendarium ,de J.R.R. Tolkien. Es uno de los personajes principales, aparte de ser uno de los cinco Istari (Magos), que fueron enviados para combatir a Sauron, siendo el último de ellos en llegar.",
    "Se le conocía de muchas maneras, Gandalf era el nombre que más se usaba; Mithrandir le llamaban los elfos y hombres de Gondor; Incánus, entre los hombres del sur; Tharkûn, entre los enanos y Olórin, en las Tierras Imperecederas, siendo éste su nombre original.",
    "Cuentos y aventuras brotaban por dondequiera que pasara, de la forma más extraordinaria."],
    informacion: {
    
    'Descripción': ["Cuando llegó a la Tierra Media tomó forma de anciano, es alto (de 1,80 cm.), tiene una barba larga y blanca hasta más abajo de la cintura, nariz aguileña y cejas largas y espesas, más sobresalientes que el ala del sombrero, que le ensombrecía la cara. Al principio se le conocía como Gandalf el Gris por su vestimenta, que era una larga capa de color gris y un sombrero alto y puntiagudo de color azul. También portaba una bufanda de plata y unas botas negras. Solía fumar en una pipa de barro.",
                    "Se comenta que Tolkien se inspiró en el dios nórdico Odín cuando se manifestaba como el Viajero para vestir a Gandalf. Con esta apariencia y color se le conocería como el que menor importancia tenía dentro de los Istari, aunque al llegar a la Tierra Media, Círdan supo ver su grandeza de espíritu y le entregó uno de los Tres anillos, Narya, el Anillo de Fuego, con el que infundiría valor y esperanza allí donde pasara.",
                    "Después de su resurrección, tras haber derrotado a un Balrog de Morgoth en Moria (Khazad-Dûm), se transformó en Gandalf el Blanco, 'Caballero Blanco', o Saruman como debería haber sido.",
                    "Fue un miembro poderoso del Concilio Blanco, tanto, que incluso Galadriel le propuso como líder del mismo, cosa que Saruman rechazó, ya que él era el Jefe del Concilio y tenía sus propios intereses. Gandalf también lo rechazaría ya que no quería estar atado a otros excepto a quienes lo enviaron a la Tierra Media. Tras guiar a Thorin y Compañía hasta el Bosque Negro, participó en la expulsión del Nigromante de Dol Guldur, y más tarde reapareció en la Batalla de los Cinco Ejércitos."],
    'En El Hobbit': ["Conodido por los hobbits de La Comarca como el mago errante que dio al Viejo Tuk un par de botones mágicos de diamante que se abrochaban solos y no se desabrochaban hasta que les dabas una orden. Quien contaba en las reuniones con los hobbits aquellas historias maravillosas de dragones y trasgos y gigantes y rescates de princesas y la inesperada fortuna de los hijos de madre viuda. El hombre que acostumbraba a fabricar aquellos fuegos de artificio tan excelentes. Se sabe que era el responsable de que tantos y tantos jóvenes hobbits apacibles partiesen hacia el Azul en busca de locas aventuras. Cualquier cosa desde trepar a los árboles a visitar elfos, o zarpar en barcos y navegar hacia otras costas. En un tiempo tuvo la costumbre de perturbarlo todo en La Comarca.",
                    "Un tiempo antes de 2941, mientras Thorin está en Bree, de camino hacia las Montañas Azules, Gandalf, quien ya estaba allí, lo encuentra y se acercó a hablar con él. Gandalf lo incitó a pensar en Erebor y  en los tesoros antaño de los Enanos que allí estaban en manos de Smaug. Terminaron organizando la expedición a recuperar Erebor.",
                    "Así, junto a Thorin, organizó la expedición a recuperar Erebor, eligiendo a Bilbo como décimo cuarto integrante de la Compañía. Después del encuentro en la casa de Bilbo Bolsón, llegan al Bosque de Trolls donde Gandalf convierte a los Trolls en piedra. No muy lejos de ahí encuentran un tesoro de Trolls, donde Gandalf encuentra tres espadas, Glamdring para él, Orcrist para Thorin y Dardo para Bilbo.",
                    "Luego llegan a Rivendel, donde se quedan un breve tiempo y parten a las Montañas Nubladas donde luego de encontrarse entre un Batalla de Gigantes de piedra, descubren una gruta y se resguardan en ella. Gandalf se despierta (por el chillido de Bilbo) justo a tiempo para matar un par de Trasgos y escapar gracias a las águilas. Llegan a casa de Beorn donde él les ayuda luego abandona, a Bilbo y a los Enanos. Después llega a Dol Guldur con Radagast, tras eso llega a la Montaña Solitaria y participa en Batalla de los Cinco Ejércitos. Gandalf fue el único mago que estudió la ciencia de los hobbits gracias a ello se hizo muy amigo de Bilbo y gracias a esto también de Frodo."],
    'Guerra del Anillo y regreso a las Tierra Imperecederas': ["Tuvo un papel fundamental durante la Guerra del Anillo, ya que descubrió la localización del Anillo Único en manos del hobbit Bilbo Bolsón en la Comarca. Sin embargo, sus sospechas no se confirmarían hasta que investigó todos los datos posibles de la historia del Anillo en las bibliotecas de Gondor e interrogó a Gollum (cuya captura y entrega encomendó a un excelente cazador y buen amigo suyo), labores por las que se no volvió a La Comarca en nueve años.",
                                                                "Cuando Bilbo deja la comarca para dirigirse a Rivendel, le deja a su sobrino Frodo todas sus posesiones, entre ellas el Anillo único Gandalf le pide que evite al maximo el uso de él, a partir de 3004 T. E., Gandalf empieza a hacer visitas periódicas a Frodo para tener el anillo vigilado. En 3018 T. E., Gandalf realiza su última visita a Frodo. Para ese entonces, Gandalf ya tiene la certeza de que el anillo de Frodo es el Anillo Único, y le advierte al hobbit sobre el peligro que corre al tenerlo, ya que su dueño Sauron desea recuperarlo. Para evitar que el Único caiga en poder del mal, Frodo emprende su viaje con él, en primera instancia hacia Rivendel, en el camino Gandalf encuentra a Radagast el Pardo quien le comunica que Saruman requiere urgente de su presencia, por lo que se despide de Frodo, indicándole que le vería en Rivendel.",
                                                                "La razón del llamado de Saruman, como descubrió una vez en Isengard, era el de comunicarle su intención de hacerse con el Anillo y ofrecerle un lugar en el régimen que fundaría una vez que derrotase a Sauron pero Gandalf se negó y el Mago Blanco lo aprisionó en una celda de Orthanc. Sin embargo, logró escapar subido en el Águila Gwaihir hasta Edoras aprovechando que Saruman apenas prestaba atención a los animales. Allí, trató de advertir al Rey Theoden, quien no le hizo caso y, en su lugar, le invitó a que escogiera un caballo de sus establos para marcharse. Gandalf escogió a Sombragrís, un caballo 'muy de su gusto pero no del rey', descendiente directo de Felaróf (el caballo blanco de Eorl), al que persiguió por tres días antes de lograr amansarlo y montarlo hasta Rivendel. Participó en el Concilio de Elrond donde habló a todos del Anillo y se ofreció a guiar a Frodo y a la Compañía del Anillo en su viaje. Desgraciadamente, en Moria se separó de la Compañía, al enfrentar al Daño de Durin, un Balrog de Morgoth que se había aseñoreado de Moria.",
                                                                "La batalla los llevaría a caer del Puente de Khazad-dûm a las profundidades de la Tierra y, de ahí, a lo alto del Celebdil, donde Gandalf abatiría finalmente al Daño. Sin embargo, las heridas del Mago era graves y murió. Sin embargo, el Vala Manwë no podía permitir que muriera sin completar su misión por lo que lo hizo volver de entre los muertos más poderoso que nunca y lo envió por Gwaihir a Lothlórien, donde se le impusieron sus ropas blancas.",
                                                                "Así convertido en Gandalf el Blanco y montado en Sombragrís, volvió a Rohan, donde se reencontró con los Tres cazadores (Aragorn, Legolas y Gimli) y fue con ellos a Edoras a salvar al Rey Theoden de la influencia de Saruman y Gríma Lengua de Serpiente.",
                                                                "Gracias a esto, los Rohirrim pudieron plantar cara a los ejércitos de Isengard en el Abismo de Helm. Sin embargo, Gandalf no participó en la Batalla hasta los últimos compases ya que, consciente de la inferioridad numérica de los defensores, se separó de la hueste de Theoden a fin de reunir a los hombres del Folde Oeste bajo el mandato de Erkebrand, dispersos después de la Segunda Batalla de los Vados del Isen, y llevarlos al Abismo en ayuda del Rey. Con la ayuda de Peregrin Tuk avisó que Gondor estaba en peligro y fue donde se libró la ultima batalla en los pueblos libres de los hombres.",
                                                                "Tras haber cumplido su misión, parte desde los Puertos Grises junto a Galadriel, Elrond, Bilbo y Frodo hacia las Tierras Imperecederas (Valinor), su hogar."],
    'En la gran pantalla':["Tanto en la trilogía cinematográfica de Peter Jackson como en El Hobbit: Un viaje inesperado es interpretado por el actor inglés sir Ian McKellen (conocido también por interpretar a Magneto en la saga X-MEN), nominado al Óscar como Mejor actor de reparto por La Comunidad del Anillo."]
    }

}