let saruman = {
    nombre: 'Saruman',
    ficha: {
        'Raza': 'Istari y Ainur',
        'Nacimiento': 'Primera Edad del Sol',
        'Muerte': '3019 de la Tercera Edad del Sol',
        'Títulos': 'Saruman El Blanco, Saruman El Sabio',    
    },
    image: 'images/personajes/saruman.jpg',
    indice: ['Historia', 'Adaptaciones','Personalidad'],
    introducción: ['Saruman el Blanco, auto nombrado por el mismo como Saruman el Sabio, Saruman el Hacedor de Anillos y Saruman el Multicolor, fue el líder de la Orden de los Istari. También era el Jefe del Concilio Blanco. Se dedicaba a estudiar las artes del Enemigo con el fin de derrotarlo, pero se interesó tanto en ello que terminó siendo atraído por el mal, y ambicionando para sí mismo el Anillo Único, él fue uno de los mayores antagonistas de los acontecimientos sucedidos en la Guerra del Anillo.'],
    informacion: {
        'Historia': ["En Valinor, Saruman, conocido como Curumo, era un Maiar al servicio de Aulë.",
                    "Cuando los Valar acordaron enviar emisarios a la Tierra Media, Curumo fue uno de los Maiar que se ofreció como voluntario. Sus celos de Olórin (más conocido como Gandalf) comenzaron cuando este último fue enviado por el señor de los Valar, Manwë, en persona, y halagado por Varda. A Curumo se le encargó llevar a Aiwendil para complacer a Yavanna, algo que no le agradó.",
                    "Cuando los Istari finalmente llegaron a la Tierra Media, Saruman acompañó a los Magos Azules al Este, pero después de 1500 años volvió cuando Sauron incrementó su poder en Dol Guldur.",
                    "El Concilio Blanco fue formado en el año 2463 de la Tercera Edad, y Saruman fue elegido como su líder, pese a que Galadriel prefería que hubiese sido Gandalf. En cuanto comenzó a sentir el resurgimiento de Sauron, Saruman comenzó a envidiar y desear su poder, y a codiciar el Anillo Único para sí mismo.",
                    "Saruman descubriría que un Palantír aún permanecía en la torre de Orthanc. Saruman ofreció al rey Fréalaf de Rohan y al senescal Beren de Gondor quedarse a vivir en Isengard para comandar las defensas del Oeste. Entonces, en el año 2759, Saruman recibió las llaves de Orthanc, ya que se esperaba que el Mago fuera un importante aliado. Saruman comenzó a usar la Palantír de Orthanc, pero se lo ocultó al Concilio Blanco.",
                    "En el año 2851, Gandalf confirmó al Concilio Blanco que Sauron estaba recuperando sus fuerzas en Dol Guldur. Sin embargo, Saruman no aprobó un ataque en la fortaleza, ya que esperaba que, con el resurgimiento de Sauron, el Anillo Único se revelara, y así Saruman iría a por él antes que Sauron lo consiguiese.",
                    "Diez años después, el Concilio Blanco se reunió por última vez, y Saruman tranquilizó a los demás sabios afirmando que el Anillo Único había sido arrastrado al mar por las aguas del Anduin. Saruman se autoproclamó señor de Isengard, comenzó a ayudar a los enemigos de Rohan y se hizo de varios espías para seguir a Gandalf, de éste modo se enteró de la existencia de la Comarca, y del interés de Gandalf por esa región. Saruman luego enviaría más espías y agentes a Bree y la Cuaderna del Sur.",
                    "Estudiando los secretos de los antiguos Noldor, Saruman creó un anillo de poder menor para incrementar sus habilidades, y se volvió un poderoso encantador con el uso de su voz. Cerca del año 3000, el uso extensivo del Palantír de Orthanc hizo que Saruman fuese tentado por Sauron (quien poseía su propia piedra vidente), de este modo uniéndose a él y completando su corrupción.",
                    "Tuvo a varios servidores: espías en Bree y en la Comarca, a Gríma Lengua de Serpiente en la corte de Rohan. Entre sus Capitanes más importantes están: Uglúk, Mauhúr y Lurtz (este sólo en las películas).",
                    "<h2>La Guerra del Anillo</h2>",
                    "Saruman comenzó a debilitar a Rohan comprando la lealtad del consejero del rey Théoden, Gríma Lengua de Serpiente.",
                    "En el año 3018 se enteró, por medio de Gandalf, de que el Anillo Único había sido descubierto y que estaba en la Comarca. Saruman reveló sus verdaderas intenciones a Gandalf, renunciando a su título de 'el Blanco' y haciéndose llamar 'Saruman el Multicolor'. Saruman ordenó a Gandalf que se rindiera ante él o ante Sauron, y cuando se negó, lo hizo aprisionar. Saruman entonces alistó un ejercito de Orcos, Uruk-hai y Dunlendinos, deforestó Isengard y parte del bosque de Fangorn y construyó túneles y fraguas subterráneas para preparar a su ejército y construir sus máquinas. Gandalf luego escaparía de Orthanc encima de una de las Grandes Águilas, y la traición de Isengard sería revelada a los demás sabios durante el Concilio de Elrond tiempo después.",
                    "Saruman traicionó a Sauron al mentirle al Rey Brujo cuando éste vino a Isengard, fingiendo no saber nada sobre la ubicación de la Comarca o el Anillo. Sin embargo, los Nazgûl descubrieron su engaño cuando capturaron a uno de los espías de Saruman en la Comarca, quien le contó todo al Rey Brujo. Revelado como un traidor tanto a Mordor como a los Pueblos Libres, Saruman se estableció como una potencia independiente y mantuvo todos sus esfuerzos en encontrar el Anillo Único.",
                    "Saruman mandó una red de espías a las cercanías de la Comarca y grupos de asaltantes para alcanzar a la Compañía del Anillo durante el transcurso de la Guerra del Anillo. Los espías fueron incapaces de capturar a Frodo Bolsón; uno de los grupos de incursión, capitaneado por el uruk Uglúk, enfrentó a la Compañía en Amon Hen y capturó a los hobbits Pippin y Merry, sin embargo los orcos fueron destruidos por los rohirrim al mando de Éomer y los hobbits escaparon a Fangorn. Saruman movilizó a un ejército gigantesco, compuesto principalmente de Uruk-hai, para atacar Rohan y destruirlo. Sin embargo, su ejército fue derrotado en el Abismo de Helm, e Isengard arrasado por los furiosos Ents, en venganza por la destrucción de Fangorn.",
                    "Tras esto, Saruman sería confrontado por Gandalf el Blanco en Isengard. Aunque tras su derrota había considerado arrepentirse, Saruman hizo un último intento por atraer a Gandalf y Théoden a su causa, luego de esto, Gandalf destruyó el bastón de Istari de Saruman, y lo expulsó de la orden. Gríma lanzó el Palantír de Orthanc fuera de la torre. Saruman fue aprisionado, junto a Gríma, dentro de Orthanc, y resguardado por los Ents.",
                    "Tiempo después de la caída de Sauron, Saruman usó el poder de su voz para convencer a Bárbol de que lo dejase ir. Los Ents liberaron a Saruman y Gríma, quienes se marcharon de Isengard, encontrándose con la Compañía del Anillo mientras pasaban por las Tierras Brunas, sin embargo, debido a que Saruman había perdido casi todo su poder, no se preocuparon por su escape. Saruman se dirigió a la Comarca y la conquistó para vengarse de los hobbits, a los cuales había subestimado. Cuando Frodo Bolsón y Samsagaz Gamyi regresaron de su viaje, organizaron una pequeña fuerza para liberar la Comarca de los espías y rufianes de Saruman. Despojado de su poder y de sus aliados, Saruman fue expulsado de Bolsón Cerrado por Frodo. Saruman trató de matar a Frodo acuchillándolo, pero el hobbit fue protegido por su cota de malla hecha de mithril. Humillado, Saruman se dispuso a abandonar la Comarca, pero fue acuchillado por Gríma en la garganta por no tolerar ya ni insultos ni desprecios. Inmediatamente después Gríma fue asesinado por los hobbits.",
                    "El espíritu de Saruman, que era un Maia, no fue admitido para volver a Valinor, y tras su muerte, un fuerte viento del oeste lo empujó lejos, completamente despojado de su poder y su forma."
                    ],
        'Adaptaciones': ["En las películas de Peter Jackson, es interpretado por el veterano actor Christopher Lee. Como curiosidad, Lee fue un gran fanático de J.R.R. Tolkien y el único miembro del reparto en haberlo conocido personalmente. Lee anhelaba personificar a Gandalf, pero debido a su edad y su potente voz fue escogido como Saruman.",
                        "Saruman es mostrado con algunas diferencias respecto al libro, por ejemplo, en las películas su objetivo es gobernar la Tierra Media al lado de Sauron, en lugar de buscar el Anillo Único por su cuenta. Su muerte (sólo mostrada en la versión extendida de El Retorno del Rey) ocurre en Isengard en lugar de la Comarca (todo el saneamiento de la Comarca fue cortado de la película por razones de tiempo), donde, luego de ser confrontado por la Compañía, es acuchillado en la espalda por Gríma tras golpearlo y humillarlo. Saruman cae encima de una rueda con estacas, y su cuerpo se hunde en la anegada Isengard al girar la rueda.",
                        "Christopher Lee es famoso a nivel mundial por haber interpretado innumerables veces el papel de Drácula, por lo que a Jackson le pareció un bello guiño que Saruman sea traicionado por su sirviente (Grima Lengua de Serpiente) y que al caer sea atravesado por una estaca de madera.",
                        "Aunque no sale en el libro original, Lee repitió su papel para las películas de El Hobbit, ya que estas adaptaban la subtrama del Concilio Blanco y Sauron que en el libro sólo es una mención fugaz. En El Hobbit: Un Viaje Inesperado, Saruman aparece en una reunión del Concilio Blanco donde refuta las evidencias de Gandalf de la existencia de un 'Nigromante' en Dol Guldur y del regreso de los Nazgûl. En El Hobbit: La Batalla de los Cinco Ejércitos, Saruman y el resto del Concilio acuden a Dol Guldur y él combate con los Nazgûl mientras Gandalf es rescatado. En esta adaptación es Galadriel quien expulsa a Sauron de la fortaleza, aunque según los libros, Gandalf cuenta que fue Saruman quien tomó protagonismo en la expulsión."
                        ],
        'Personalidad': ["Saruman ha demostrado ser calculador, inteligente y muy astuto. Cuando fue siendo atraído por el poder del Anillo Único mostró su personalidad maliciosa y sedienta de poder, pero manteniéndose tranquilo hacia cualquier situación (excepto si está en desventaja)."],
    
    }

}