let el_hobbit_un_viaje_inesperado_pelicula = {
    nombre: 'El Hobbit: Un viaje inesperado',
    ficha: {
        'Director': 'Peter Jackson',
        'Año de estreno': '2012',
        'Duración': '169 minutos',
        'Género': 'Fantasía heroica, aventuras, acción, drama',
    },
    image: 'images/peliculas/el_hobbit_un_viaje_inesperado.jpg',
    indice: ['Descripción', 'Etimología', 'Argumento', 'Sinopsis', 'Producción'],
    introducción: [
        'El Hobbit: Un Viaje Inesperado (The Hobbit: An Unexpected Journey en el original inglés), es la primera parte de la Trilogía cinematográfica de El Hobbit, basada en el libro de El Hobbit, escrito por J.R.R. Tolkien. Es seguida por El Hobbit: la desolación de Smaug.'
    ],
    informacion: {
        'Descripción': ['El hobbit: un viaje inesperado fue la primera película de la historia en haber rodado a 48 fotogramas por segundo, un formato conocido como 3D HFR (por emitirse al doble de fotogramas y 5K de resolución).'],
        'Etimología': ['Aunque el libro original estaba formado por un solo volumen, la adaptación cinematográfica será dividida en tres partes; las cuales tendrán un subtítulo cada una. Un viaje inesperado es el subtítulo de la primera parte, el cual parece estar inspirado en uno de los títulos que Bilbo quiso poner al Libro Rojo (Mi Viaje Inesperado), donde recogía sus aventuras y las de Frodo, pero al final el título fue tachado junto a los otros para finalmente llamar al libro La Caída del Señor de los Anillos y El Retorno del Rey. También es probable que el título de Un Viaje Inesperado esté inspirado en el nombre del primer capítulo de El Hobbit, llamado Una Tertulia Inesperada.'],
        'Argumento':[
            'La aventura cuenta el viaje de Bilbo Bolsón, quien se ve arrastrado a una épica búsqueda que le llevará a reclamar el reino que años atrás perdieron los enanos a manos del temible dragón Smaug. Sin verlo venir, y convencido por el mago Gandalf el Gris, Bilbo termina formando parte de una compañía de 13 enanos liderados por el legendario guerrero Thorin Escudo de Roble.',
            'Su viaje les llevará a lo salvaje, a través de tierras peligrosas infestadas de trasgos, orcos y huargos mortíferos, así como de una misteriosa y siniestra criatura conocida como El Nigromante. A pesar de que su destino está situado al Este, en las tierras yermas de la Montaña Solitaria, los personajes primero tendrán que escapar de los túneles de los trasgos, donde Bilbo conocerá a la criatura que cambiará su vida para siempre… Gollum.',
            'A orillas de un lago subterráneo será cuando el modesto Bilbo, al quedarse a solas con Gollum, descubra no solo la profundidad del ingenio y el coraje, hecho que le sorprende incluso a él, sino que además se apoderará del “precioso” anillo de Gollum, un anillo con inesperadas cualidades y de gran utilidad… Una sencilla sortija de oro que está ligada de tal manera al destino de toda la Tierra Media que Bilbo no es capaz siquiera de imaginar.'
        ],
        'Sinopsis':[
            '<h2>La Tertulia Inesperada</h2>',
            'Un anciano hobbit Bilbo Bolsón está punto de cumplir 111 años, y decide escribir para su sobrino Frodo la narración completa sobre el inesperado viaje en el que se embarcó hace sesenta años. Comienza narrando la historia del fabuloso reino enano de Erebor, bajo la Montaña Solitaria, en la que los enanos extraían metales preciosos bajo el reinado de Thrór, el rey bajo la montaña. Sin embargo, tales riquezas despertaron la codicia de Smaug, el más grande de los dragones del Norte, y atacó Erebor y la Ciudad de Valle, expulsando a los enanos de su reino y apoderándose del ingente tesoro.',
            'Desde entonces, los enanos de Erebor se convirtieron en un pueblo errante y vagaron por muchas tierras, pero nunca olvidaron el ataque de Smaug y el viejo reino que les pertenecía. Tras contar la historia de Erebor, Bilbo pasa a relatar sus aventuras, iniciadas años atrás, cuando, en una apacible mañana mientras fuma delante de su agujero-hobbit, se encuentra con el mago Gandalf el Gris. Gandalf busca a alguien aventurero, pero Bilbo se niega rotundamente, ya que aborrece las aventuras tanto como todos los hobbits de la Comarca.',
            'En la tarde del día siguiente, Bilbo casi no se acordaba de la cita con Gandalf cuando oye llamadas en la puerta. Del todo perplejo, ve cómo varios enanos se presentan en su casa saludando como quien no quiere la cosa y preparan una cena. Finalmente, se presenta Gandalf para estar presente en la reunión y esperan la llegada de un enano que parece ser de alto rango, nada más y nada menos que Thorin Escudo de Roble, príncipe enano nieto de Thrór, el último Rey Bajo la Montaña.',
            '<h2>El viaje hacia Rivendel</h2>',
            'Bilbo se despierta la mañana siguiente con la sensación de que la visita de los Enanos fue sólo un sueño, al descubrir que anoche le dejaron una nota diciendo que si quería aceptar el trabajo de saqueador, que se reuniera con ellos en Delagua. Sin saber él mismo lo que hace, un extraño sentimiento aventurero lo incita a salir de su agujero y correr apresuradamente a Delagua a reunirse con la Compañía de Thorin. Allí, con cierto pesar, descubre que la mayoría de los enanos no pensaban que se atreviera a acompañarles y habían hecho una apuesta en la cual ganan Balin y Gandalf, que confía en el hobbit y sabe que es capaz de hacer más de lo que piensa.',
            'Así, de este modo, Bilbo se embarca con Gandalf y los enanos de Thorin en una expedición hacia el Este. El primer problema surge atravesando el Bosque de los Trolls, donde los trece enanos son atrapados por los trollsBerto, Tom y Guille. Bilbo, a pesar de temblar de pies a cabeza, logra entretenerles lo suficiente hasta el amanecer, momento en el que Gandalf los expone a la luz del sol y los trolls se convierten en piedra. No muy lejos encuentran la guarida de los tres trolls, donde Gandalf toma a Glamdring, una espada que habían robado los trolls; y entrega una pequeña daga a Bilbo (a la que pone el nombre de Dardo), que brilla cuando hay Orcos cerca. Por su parte, Thorin toma a Orcrist.',
            'Cerca del Vado del Bruinen, el grupo se encuentra un día de improviso con Radagast el Pardo, un mago de la Orden de los Istari, a la que pertenece Gandalf y el resto de magos. Radagast le cuenta a Gandalf temerosamente que en el Gran Bosque Verde, donde él vive, el mal está volviendo al bosque debido a que un misterioso Nigromante se ha instalado en Dol Guldur, una antigua fortaleza que pertenecía a Mordor, ahora en ruinas, construida antes de la segunda derrota del Señor Oscuro. En ese mismo momento, un grupo de Orcos montados en Wargos ataca al grupo, que logra escapar al valle secreto de Rivendel gracias a que Radagast los distrae y un grupo de Elfos de Elrond aparece de repente.',
            '<h2> El Concilio Blanco</h2>',
            'En Rivendel, Elrond, su señor, acoge a la Compañía de Thorin, aunque los enanos no se encuentran muy a gusto debido a que en el pasado el rey Thranduil de los Elfos del Bosque Negro no les ayudó cuando cayó Erebor. Galadriel, Dama de Lórien, y Saruman el Blanco, líder de los Istari; también se encuentran en Rivendel, debido a que se encuentran enterados del mal que ha surgido en el Bosque Negro. Así pues, en Rivendel tiene lugar el Concilio Blanco entre Elrond, Galadriel, Gandalf y Saruman. Gandalf sospecha que el Nigromante no es otro que Sauron, ya que no fue destruido del todo debido a la pérdida del Anillo Único por parte de Isildur. Sin embargo, la opinión de Saruman prevalece, y opina que el Anillo Único se ha perdido para siempre bajando del Anduin al Mar, añadiendo que el Nigromante sea seguramente el Rey Brujo con una nueva ofensiva. Mientras tanto, en Amon Sûl, los orcos que habían atacado a Thorin y Compañía en el Vado del Bruinen avisan a su señorAzog de que el Enano Thorin Escudo-de-Roble está vivo. Thorin había herido seriamente a Azog en años pasados, en la Batalla de Nanduhirion delante de las Minas de Moria, y Azog ha jurado vengarse de él desde entonces.',
            '<h2> Bajo las Montañas Nubladas </h2>',
            'En Rivendel, Thorin, Bilbo y los doce enanos parten de nuevo mientras Gandalf continúa en el Concilio. Para continuar el viaje deben cruzar las peligrosas Montañas Nubladas, en las que un día de tormenta sobre ellas presencian un impresionante combate entre Gigantes de Piedra. Para refugiarse de la titánica batalla, se refugian en una cueva. Bilbo, tras ver los peligros de las Montañas, cree que ha visto demasiado y se dispone a volver a su país por su cuenta mientras los enanos duermen. Bofur sin embargo lo descubre, y cómo cree en él Bilbo decide quedarse. Sin embargo, Thorin, al que no le había gustado el hobbit, lo toma como que Bilbo no le interesa la expedición y que sólo será un estorbo.',
            'En ese momento, una grieta se abre en la cueva y multitud de Trasgos les salen al encuentro y capturan al grupo, pues la cueva era una de las muchas entradas de un sistema de túneles de trasgo. Bilbo y Thorin y Compañía son conducidos al Gran Trasgo, que les acusa de querer robar y ordena matarles. En ese momento, Gandalf aparece y acaba con el jefe trasgo, y algunos más. Thorin, Gandalf y los enanos huyen precipitadamente, pero Bilbo se cae y se separa del grupo, cayendo en una cueva en cuyo suelo encuentra un anillo misterioso. Bilbo lo guarda sin más y llega a un lago subterráneo, donde Gollum, una vieja criatura hambrienta que habla con un tal "tesoro" le propone jugar a los acertijos. Si Bilbo ganara, le mostraría la salida de los túneles, pero si el ganador fuera Gollum, se comería al hobbit.',
            'Los dos van cuestionando adivinanzas extrañamente parecidas y finalmente Bilbo, nervioso jugetea con el Anillo que guarda en el bolsillo, preguntándose a él mismo <<¿Qué tengo en el bolsillo?>>. Gollum lo interpreta como un acertijo, y al no acertarlo, en lugar de cumplir su promesa se dispone a ir a su isla del lago, donde guarda a su "tesoro", un anillo mágico que hace invisible a quien se lo pone en el dedo, pretendiendo matar a Bilbo por sorpresa. Al no encontrarlo, Gollum, muy alterado, descubre que Bilbo tiene su anillo, que debió caérsele mientras cazaba a un trasgo. Gollum se dispone a acabar con Bilbo, pero éste logra verlo de lejos y, casualmente, al meter una mano el bolsillo, el anillo se le desliza al dedo y Bilbo descubre que el objeto lo hace invisible. Bilbo aprovecha esta propiedad para seguir a Gollum y buscar cualquier salida. En cierto punto, se tienta a atravesar a Gollum con la espada, pero un sentimiento compasivo lo hace apiadarse de él.',
            '<h2>En las Tierras Salvajes</h2>',
            'Bilbo se reúne de nuevo con el grupo de Thorin al oír sus voces, pero no le dice nada a nadie sobre el encuentro del Anillo. Tras una persecución por la subterránea Ciudad de los Trasgos, la compañía de Thorin, Gandalf y Bilbo salen al exterior sólo para caer ahora en terreno de una manada de wargos, que se pone a perseguirlos immediatamente. Los quince miembros se suben a un abeto situado al lado de un barranco para salvarse de los wargos cuando descubren que la manada estaba capitaneada por el orco Azog, que iba en busca de Thorin. Nada más verse, Azog y Thorin salen al encuentro para enfrentarse, pero Thorin recibe un golpe del orco que lo tira al suelo. Un inesperado golpe de valentía aparece en Bilbo, que baja del árbol también para proteger a Thorin a pesar del miedo que siente. Los otros enanos lo siguen para enfrentarse a los otros orcos de Azog en un desesperado combate.',
            'Por suerte, un grupo de Águilas, amigas de Radagast, baja de las alturas de las Montañas y recogiendo a los miembros de la Compañía de Thorin, los trae a un lugar seguro que mira al este, sobre el Río Grande y el Bosque Negro, divisándose, bien lejos, la Montaña Solitaria. El grupo está ya en las Tierras Salvajes, y Thorin, que estaba inconsciente por la caída, se reanima y pide perdón a Bilbo por su desconfianza, llego de gratitud hacia el hobbit por haberle salvado. Mientras los viajeros contemplan su destino, un zorzal levanta el vuelo y llega a la Montaña Solitaria, donde captura un caracol y lo golpea contra una piedra para engullirlo. El eco de los golpes resuena en el interior de la montaña, donde el dragón Smaug despierta dando final a la película.'
        ],
        'Producción':[
            'Una adaptación cinematográfica de la novela de J. R. R. Tolkien El hobbit (1937) estuvo en desarrollo durante varios años después del éxito crítico y financiero de la trilogía cinematográfica de El Señor de los Anillos (2001-2003), coescrita, coproducida y dirigida por Peter Jackson. Jackson inicialmente iba a producir una adaptación de dos partes de El hobbit, la cual iba a ser dirigida por Guillermo del Toro. Del Toro dejó el proyecto en mayo de 2010, luego de unos dos años de trabajar con Jackson y su equipo de producción, debido a retrasos causados en parte por los problemas financieros de la Metro-Goldwyn-Mayer. Jackson fue anunciado como director ese mismo octubre.',
            'Las películas de El hobbit fueron producidas consecutivamente, como las películas de El Señor de los Anillos. El rodaje de las películas de El hobbit comenzó el 21 de marzo de 2011 en Nueva Zelanda y finalizó el 6 de julio de 2012, luego de 266 días de filmación. Además, algunos pick-ups de Un viaje inesperado fueron rodados en julio de 2012. El trabajo en la película fue completado el 26 de noviembre, justo dos días antes del estreno de la película en Wellington.',
            '<h2>Banda sonora</h2>',
            'La banda sonora de Un viaje inesperado fue compuesta por Howard Shore. Fue realizada por la Orquesta Filarmónica de Londres y presentó a varios solistas. La canción original «Song of the Lonely Mountain», cantada por Neil Finn, sirvió como el tema de los créditos. El álbum recibió nominaciones para varios premios y alcanzó el punto máximo en los diez primeros éxitos en Corea y Estados Unidos.'
        ]

    
    },

}

let el_hobbit_la_desolacion_de_smaug_pelicula = {
    nombre: 'El Hobbit: La desolación de Smaug',
    ficha: {
        'Director': 'Peter Jackson',
        'Año de estreno': '2013',
        'Duración': '161 minutos',
        'Género': 'Fantasía heroica, aventuras, acción',
    },
    image: 'images/peliculas/el_hobbit_la_desolacion_de_smaug.jpg',
    indice: ['Etimología', 'Argumento', 'Sinopsis', 'Producción'],
    introducción: [
        'El Hobbit: la desolación de Smaug es la segunda parte de la trilogía cinematográfica de El Hobbit. Continúa relatando los acontecimientos de la novela de J.R.R. Tolkien de El Hobbit, como continuación de El Hobbit: Un Viaje Inesperado, la primera película de la trilogía. Dirigida por Peter Jackson, fue estrenada el 13 de diciembre de 2013.',
        'En ella, Bilbo, Gandalf y la Compañía de Thorin continúan en su viaje para reconquistar el reino de Erebor que arrebató el dragón Smaug, pero para ello deberán enfrentarse a diversas aventuras y a un antiguo mal que está volviendo a la Tierra Media.'
    ],
    informacion:{
        'Etimología':['Aunque originalmente, cuando la adaptación cinematográfica de El Hobbit fue acordada en dividirse en dos películas, la segunda parte se iba a llamar Battle of Five Armies (Batalla de Cinco Ejércitos), en convertirse en trilogía se cambió el nombre para llamarse La Desolación de Smaug. El título hace referencia tanto a la situación crítica a la que los personajes llegan al encontrarse con Smaug y también al nombre que recibe la árida región que se extiende alrededor de la Montaña Solitaria.'],
        'Argumento':['Tras cruzar las Montañas Nubladas y lograr escapar del malvado Azog, Bilbo Bolsón, Thorin y el resto de la compañía continúan su viaje hacia Erebor, con la idea de vencer al dragón Smaug y recuperar así su hogar y el gran tesoro que allí les aguarda. Pero antes deberán atravesar el sinuoso bosque negro, donde habitan los Elfos silvanos, comandados por el rey Thranduil, cuya relación con Thorin no es especialmente amistosa. Por el camino se toparán además con otros personajes y criaturas que intentarán ayudarles u obstaculizar su misión, y Bilbo se dará cuenta de la gran utilidad del anillo. Por su parte el mago Gandalf intentará desentrañar el enigma de «El Nigromante», y descubrirá que sus peores sospechas eran ciertas; el enemigo de los pueblos libres de la Tierra Media ha regresado.'],
        'Sinopsis':[
            '<h2>Preludio: Encuentro en Bree</h2>',
            'La película comienza con un flashback situado 12 meses antes de la trama. Thorin Escudo de Roble, durante un viaje, se aloja en la posada El Poney Pisador de Bree, en la que se reúne casualmente con el mago Gandalf el Gris. Gandalf le advierte que alguien quiere verlo muerto, y evitar que recupere su trono del reino de Erebor. Thorin decide entonces formar una compañía para viajar a la Montaña Solitaria, aunque Gandalf le recomienda que lleve con él un saqueador.',
            '<h2>A través del Bosque Negro</h2>',
            'Doce meses después en el pie de las Montañas Nubladas, justo después de los acontecimientos de la primera película, el hobbit Bilbo Bolsón, saqueador de la Compañía de Thorin, avisa al grupo de que la horda de orcos de Azog continúa en su seguimiento, y que además ha visto un oso enorme patrullando por las colinas. Gandalf les dice que deben llegar a una casa de madera antes del anochecer o los orcos los alcanzarán. Apresuradamente, Bilbo, Gandalf y los Enanos  llegan a la cabaña a tiempo de escapar de el feroz oso que había visto Bilbo. Gandalf revela entonces que el enorme animal es el propietario de la casa, y es en realidad un cambia-pieles llamado Beorn, que a veces es hombre y otras oso. Beorn (en forma de hombre) vuelve al día siguiente, y aunque no le gustan los enanos, decide ayudarlos ya que los orcos que los persiguen acabaron con todos los de su especie. Afuera, donde los guerreros de Azog vigilan, un mensajero orco se reúne con ellos diciéndole que el Nigromante quiere convocar a Azog en Dol Guldur. Viendo que debe ir, Azog deja a su hijo Bolgo al cargo de la exterminación de Thorin y compañía.',
            'Tomando prestados los poneys de Beorn, la Compañía de Thorin llega a la entrada del Bosque Negro. Deben cruzarlo, ya que deben llegar a la Montaña Solitaria antes del Día de Durin, y para rodearlo hay que desviarse cientos de millas. A Gandalf le inquieta la especie de enfermedad que está atacando el bosque, pues antaño era llamado el Gran Bosque Verde y era un lugar hermoso. En ese momento, Gandalf recibe un mandato de Galadriel, que le pide ir a revisar las antiguas tumbas de los Nueve. Eso obliga a Gandalf a abandonar el grupo y desearles la mejor suerte en su viaje, diciendo para tranquilizar a los enanos que se reunirá con ellos en la Montaña.',
            'Con gran pesar, los Enanos inician la travesía del Bosque Negro. Caminan con cuidado de no perder el camino, pero rápidamente caen bajo las ilusiones e encantamientos que pesan sobre el bosque. Tras lo que parece ser una eternidad de viaje, Bilbo decide subir a un árbol para intentar ver algún signo de orientación por encima de la masa forestal, pero al bajar, descubre que los enanos han desaparecido, perdiendo luego el sentido. Con horror, al despertar ve que unas Arañas Gigantes los han apresado. Sin embargo, Bilbo logra liberarse con su espada y con la ayuda de su Anillo logra cortar las telarañas que apresan a los enanos, acabando con muchas arañas. De repente, en el fragor de la batalla, un grupo de Elfos aparecen, capitaneados por Legolas  y Tauriel, que registran a los viajeros y apresan a los enanos y los conducen a una gran cueva donde reside el rey Thranduil del Bosque. Todos son encerrados en celdas, excepto Bilbo, que logra escapar gracias a que se hace invisible con su Anillo.',
            '<h2>Barriles em el Río del Bosque</h2>',
            'El rey Thranduil, que sabe que Thorin es el heredero al trono el Rey Bajo la Montaña, le ofrece ayudar a recuperar Erebor a cambio de recibir ciertas joyas que robó el dragón. Thorin se niega rotundamente porque no olvida que Thranduil no les ayudó cuando los Enanos fueron atacados por Smaug. Esto enfada al rey elfo, y ordena retener a los enanos indefinidamente. Mientras tanto, abajo en las celdas, Kíli, al que le gusta Tauriel, la entretiene con sus historias mientras monta guardia, cosa que hace que ella también empiece a sentirse atraída por el joven enano.',
            'El tiempo pasa y Thorin empieza a desesperarse cuando Bilbo aparece de la nada fuera de su celda (quitándose el Anillo), mostrando que ha quitado las llaves de las celdas al carcelero de castillo elfo, que ha bebido un vino muy fuerte. Bilbo libera a todos sus compañeros y les conduce a las bodegas, donde les ordena meterse a todos en un barril. Los enanos protestan, pero acceden finalmente al oír que los elfos han detectado su fuga. Bilbo acciona una palanca que abre una compuerta y él y trece barriles con enanos caen a una corriente subterránea que comunica con el Río del Bosque.',
            'Pronto salen al exterior, pero la alegría dura poco cuando los elfos cierran unas compuertas en el río y para colmo, el grupo de orcos comandado por Bolgo irrumpe atacando a elfos y enanos por igual. Desde ese momento, tiene una frenética batalla de tres bandos en la que los enanos se defienden como pueden y la corriente los arrastra.',
            'Finalmente se ponen a salvo ya mucho más abajo del Río del Bosque, sólo hay un herido, Kíli, que ha recibido una flecha orca en la pierna pero dice encontrarse bien. Mientras tanto, en el palacio de Thranduil, el rey elfo, su hijo Legolas y Tauriel se encuentran interrogando a uno de los orcos que han atacado. El orco responde de forma burlona, y les dice que al más joven de los Enanos de Thorin (Kíli) le han clavado una Flecha de Morgul que lo matará por dentro lentamente, declarando además de que los Elfos del Bosque no podan hacer nada contra el Amo al que sirve. En un ataque de furia, Thranduil decapita al orco y ordena cerrar todas las puertas de palacio, ya que intuye que el Amo de los orcos puede ser el Señor Oscuro. Tauriel, sin embargo, hace caso omiso de la orden de Thranduil y huye en busca de los enanos, ya que sabe que Kíli va a morir si no se hace nada.',
            '<h2> La Ciudad del Lago</h2>',
            'Mientras Thorin y Compañía descansan en un recodo el río, un hombre arquero llamado Bardo les sale al encuentro. Los enanos le dicen que son simples mercaderes, y aunque Bardo no acaba de fiarse de ellos, acepta las monedas que los enanos le ofrecen si los lleva en secreto a Esgaroth, la Ciudad del Lago, la última parada que el grupo tiene prevista antes de llegar a la Montaña. A pesar de los temores de los Enanos, Bardo no les traiciona y, navegando por el Lago Largo, les trae a la ciudad, que es de hecho donde se encuentra su casa. Aunque son vistos por algunos vecinos, Bardo les paga para que hagan la vista ciega. Los enanos se alojan así pues en casa de Bardo, en compañía de su hijo Bain y sus hijas Sigrid y Tilda. ',
            'Mientras, Gandalf llega a las remotas tumbas donde yacen los nueve Nazgûl, y con temor, descubre que se encuentran vacías: algo los ha despertado. El mago convoca a Radagast y le pide que lleve un mensaje a la dama Galadriel, avisándola del descubrimiento. Gandalf, despidéndose del despistado mago pardo, parte a Dol Guldur a investigar más sobre qué tipo de enemigo es el Nigromante y porqué todos los orcos se dirigen a la vieja fortaleza. Sabe que debe reunirse con Bilbo, Thorin y los Enanos, pero un presentimiento lo hace continuar en su investigación.',
            'A pesar de los esfuerzos de Bardo para mantener a los enanos de Thorin en secreto, la voz corre en la Ciudad del Lago y los habitantes empiezan a creer en la profecía de que el Rey Bajo la Montaña volvería y traería grandes riquezas a la ciudad. Tales historias de grandeza no gustan nada al Gobernador de Esgaroth, que considera a Bardo como un conspirador para quitarle el puesto. Finalmente, un grupo de soldados atrapa a los enanos tras vigilar la casa de Bardo, y son conducidos a la plaza principal. Allí, Thorin cuenta sus propósitos de reconquistar la Montaña y matar al dragón Smaug, cosa que causa vitoreos de los aldeanos y que también gusta al Gobernador gracias a la oportunidad de recuperar el inmenso tesoro de Erebor. Bardo advierte de que si despiertan al dragón destruirá la ciudad y no dejará a nadie vivo, pero sus opiniones son apenas oídas.',
            'Desde ese momento, Thorin, Bilbo y el resto de enanos son tratados con gran honor. Finalmente, llega el Día de Durin y los enanos deben partir para poder encontrar a tiempo la puerta secreta de la Montaña. Thorin ordena a Kíli, que ha empeorado en su herida, que se quede en la ciudad. Óin, Fíli y Bofur también se quedan para intentar curarlo. Con esto, Thorin y su disminuida compañía parten hacia la Montaña.',
            '<h2> La Desolación de Smaug</h2>',
            'Thorin y Compañía llegan al fin al pie de la Montaña Solitaria, que se alza amenazadora, nevada, y aparentemente silenciosa. El paisaje es triste y melancólico, se encuentran en la Desolación de Smaug. En una ladera, la compañía contempla las ruinas de Valle, una rica ciudad que comerciaba con Erebor la cual también fue destruida por el dragón. Bilbo avisa a Thorin de que Gandalf iba a esperarles en el mirador de esa ciudad derruida, pero no lo ven por ningún sitio. Un Thorin más frío de lo normal insta al grupo a apresurarse, y a encontrar el camino a la puerta secreta.',
            'Es Bilbo quien finalmente encuentra la senda, y escalándola, llegan a una especie de umbral donde según el Mapa de Thrór se halla la entrada secreta a la montaña. Como se dice en él, Thorin intenta encontrar alguna cerradura donde la luz poniente del sol cae sobre la pared, pero cae la noche y no ocurre nada. Desesperados, los enanos se disponen a volver cuando Bilbo encuentra la respuesta al acertijo al descubrir que la última luz del día no era la de la puesta de sol, sino la de la luna. Una puerta oculta se abre y, maravillados, los enanos penetran en su interior, emocionados por haber llegado por fin al reino de Erebor.',
            'Pero ahora toca lo más difícil, entrar en las estancias interiores de la Montaña, algo poco alentador debido a que los enanos no saben lo que pueden encontrar allí. Finalmente el elegido para ir es Bilbo, el saqueador, a quien Thorin ordena encontrar la Piedra del Arca, la más bella de las piedras preciosas de la Montaña. Balin, que se ha encariñado con el hobbit, le acompaña durante un buen trecho por los antiguos túneles y le desea la mejor suerte al llegar a la puerta de la Sala Central.',
            'En la Ciudad del Lago, mientras tanto, la manada de orcos de Bolgo invade la población en busca de Thorin Escudo de Roble. Su ataque es neutralizado por Tauriel y Legolas, que se ha unido a ella al creer las palabras de Tauriel sobre el retorno del Enemigo. Un jinete orco, sin embargo, logra escapar por uno de los puentes de la ciudad, yendo a Dol Guldur para comunicar al Amo que Escudo de Roble ya está en la Montaña Solitaria.',
            'A esa misma fortaleza llega Gandalf en esos momentos, y con un encantamiento deshace la ilusión a la que Dol Guldur se encuentra sometida. Ve entonces que hordas y hordas de orcos se encuentran en la fortificación, y Azog, que lo estaba esperando, se abalanza sobre él al verlo. Gandalf logra evitar a él y a sus orcos gracias a varios hechizos, hasta que finalmente llega en presencia del Nigromante. Éste, que tiene forma de sombra negra se burla de Gandalf, aunque el mago por su parte logra protegerse de su poder creando una barrera mágica a su alrededor. Pero ni siquiera todo el poder de Gandalf logra retener al poder de la Sombra. El Nigromante cambia de forma, y se condensa para convertirse en una forma humanoide y malvada, la cual es el centro de un enorme Ojo rojo amenazante. Gandalf, atado por las tinieblas, ve con desesperación que, tal como suponía, el Nigromante es nada más y nada menos que Sauron de Mordor, el Señor Oscuro, el mayor de los males de la Tierra Media, que ha regresado.',
            '<h2> Venganza</h2>',
            'Bilbo entra en la Sala Principal del reino de Erebor, donde, impresionado, contempla cómo toda la estancia se encuentra inundada por una inmensa montaña de monedas, joyas, piedras preciosas y todo tipo de tesoros. Bilbo se dispone a buscar la Piedra del Arca, como le pidió Thorin, pero un corrimiento seguido de monedas provocado por un mal paso del hobbit acaba formando un ruido demasiado alto. Aterrorizado, Bilbo contempla cómo de debajo de la montaña de oro se levanta un enorme ser cubierto de escamas durísimas y de ojos rojos como el fuego: el dragón Smaug despierta.',
            'Al abrir los ojos, Smaug no logra ver a Bilbo gracias a que lleva puesto el Anillo, pero es capaz de olerlo y oírlo. Con una voz intimidante, hace saber a Bilbo que sabe que está ahí. Bilbo, a pesar de tener mucho miedo, se quita el Anillo y le cuenta quién es él a Smaug mediante acertijos, cosa que gusta al dragón y lo entretiene. Durante la conversación, Bilbo logra ver la Piedra del Arca, pero no la puede alcanzar con los movimientos arrinconadores de Smaug. A pesar de los cumplidos que Bilbo le lanza al dragón, Smaug resulta más inteligente de lo que creía el hobbit y logra deducir, burlándose de Bilbo, que forma parte de un grupo de enanos capitaneados por Thorin Escudo de Roble para intentar reconquistar la Montaña. El olor de Bilbo denota olor enano, y Smaug ya esperaba algún intento de revuelta por algún enano incauto. Para acabar, Smaug lanza una gran llamarada de fuego, pero Bilbo logra esquivarla volviéndose invisible con el Anillo.',
            'En ese momento, Thorin y los enanos entran en la sala, donde Smaug los ve y confirma sus sospechas. Como no pueden defenderse de él en ese espacio, intentan refugiarse en pasillos de Erebor más pequeños. Allí algunos enanos proponen ir a las minas y aguantar, ya que el dragón no podrá atacarles por allí. Pero a Thorin no le gusta ese plan, y quiere acabar con el dragón sea como sea, para cumplir su venganza en nombre de todo el pueblo Enano. Para ello, traza un plan y los enanos deben dividirse en varios grupos, reuniéndose todos en la Zona de Forja.',
            'Mientras tanto, en la Ciudad del Lago, Kíli se encuentra agonizando por el veneno de la flecha de Morgul. Tauriel, que estaba buscándolo, se encuentra con Bofur, que ha encontrado Athelas (o Hojas de Reyes) para intentar curar al enano. Con la ayuda de Fíli, Óin, Bofur, Sigrid y Tilda (las hijas de Bardo), Tauriel pronuncia las palabras adecuadas para sanar la herida envenenada. Kíli rejuvenece, y cree que ve a Tauriel en sueños.',
            'En el interior de la Montaña, los enanos se han reunido ya en las forjas, pero Smaug también los ha encontrado a ellos. De forma muy rápida, Thorin y compañía encienden las antiguas fundiciones con ayuda, en parte, del fuego de Smaug, que se encuentra ocupado intentando echar abajo una pared para poder alcanzar a los enanos. Smaug finalmente entra en la sala, cuando de las vagonetas los enanos echan oro para fundirlo y conducirlo por los canales del suelo. El dragón va a por Thorin, pero el heredero de Thrór esquiva sus ataques. El combate se traslada a la Sala de la Entrada, donde se encuentra Bilbo. Smaug, muy enfadado por lo que están haciendo los enanos, relaciona a los enanos con los hombres de la Ciudad del Lago. Bilbo le ruega a Smaug que no ataque la ciudad, ya que sus habitantes no tienen la culpa, pero el dragón se ríe de él diciéndole que le permitirá ver cómo mueren.',
            'En ese momento, Thorin y los enanos entran en la sala subidos en un gran bloque de piedra, que es partido para mostrar una gigantesca estatua dorada de Thrór hecha del oro que han encendido en la forja. Thorin desafía a Smaug diciendo que van a tomar su venganza, y acto seguido los enanos sueltan las fijaciones para que todo el oro fundido de la estatua caiga sobre Smaug. Con un grito, Smaug es enterrado por una masa dorada de metal líquido. Cuando parece que el dragón ha sido derrotado para siempre, un temblor se produce y Smaug, ahora dorado, se alza de la masa de oro como si nada hubiera pasado, gracias a la protección de sus escamas. Furioso por el intento de venganza de Thorin, les dice a los enanos que les mostrará cómo es realmente una venganza antes de volver para matarlos. Y con esto, Smaug atraviesa la puerta principal de Erebor, haciéndola pedazos, y se dirige hacia la Ciudad del Lago, dispuesto a consumar su venganza. La película termina con una frase de Bilbo lamentándose: <<¿Qué hemos hecho...?>>.'
        ],
        'Producción': [
            'La mayor parte del rodaje se terminó en julio de 2012. Pero durante mayo de 2013 se realizó en Nueva Zelanda un rodaje adicional de 10 semanas para la película y la tercera parte.',
            '<h2>Música</h2>',
            'La banda sonora de El hobbit: la desolación de Smaug fue compuesta por Howard Shore, asociado con el equipo de escritores de Nueva Zelanda. La amplia mayoría de las pistas fueron interpretadas por la Orquesta Sinfónica de Nueva Zelanda, excepto unas pocas que se hicieron con la Orquesta Sinfónica de Londres. El álbum original de la banda sonora de la película fue lanzado el 10 de diciembre de 2013, para coincidir con el estreno de la película.',
            'El cantautor inglés Ed Sheeran escribió y grabó la canción «I See Fire», la cual suena durante los créditos. La canción fue publicada en iTunes el 5 de noviembre de 2013.'
        ]

    },

}

let el_hobbit_la_batalla_de_los_cinco_ejercitos_pelicula = {
    nombre: 'El Hobbit: La Batalla de los Cinco Ejércitos',
    ficha: {
        'Director': 'Peter Jackson',
        'Año de estreno': '2014',
        'Duración': '144 minutos',
        'Género': 'Fantasía épica, aventura, acción',
    },
    image: 'images/peliculas/el_hobbit_la_batalla_de_los_cinco_ejercitos.jpg',
    indice: ['Sinopsis'],
    introducción: [
        'El Hobbit: La Batalla de los Cinco Ejércitos (The Hobbit: The Battle of the Five Armies) es la tercera parte de la Trilogía cinematográfica de El Hobbit, basada en el libro El Hobbit de J.R.R. Tolkien y dirigida por Peter Jackson.',
        'Aunque el libro original estaba formado por un solo volumen, las adaptaciones cinematográficas fueron divididas en tres partes, las cuales tendrán un subtítulo cada una. La Batalla de los Cinco Ejércitos es el subtítulo elegido para la tercera y última parte. Este subtítulo proviene de la traducción al español de The Battle of the Five Armies en la Trilogía Cinematográfica de El Señor de los Anillos, mientras que la traducción al español en los libros es Historia de una Ida y de una Vuelta. There and Back Again o Historia de una Ida y de una Vuelta fueron los subtítulos oficiales que tenían los libros de El Hobbit en inglés y español respectivamente, aunque normalmente el título del libro se abrevia a El Hobbit sin ningún subtítulo. Este subtítulo fue uno de los títulos que tenía pensado ponerle Bilbo al libro donde recogía sus aventuras, más conocido como Libro Rojo de la Frontera.',
        'En un principio la tercera parte de la trilogía cinematográfica sería llamada Partida y Regreso, en la cual participan personajes importantes de toda la aventura en general como Thranduil, el rey del Bosque Negro (antiguamente era descrito como Bosque Verde) y Beorn el Cambiapieles.'
    ],
    informacion: {
        'Sinopsis':[
            'Bilbo y los enanos se refugian en la Colina del Cuervo mientras el dragón Smaug desata el infierno sobre la Ciudad del Lago. Bardo, que intenta acabar con el dragón infructuosamente empleando flechas que no atravesaban su piel; con la ayuda de su hijo Bain, logra matar al dragón con la última Flecha Negra que quedaba tras comprobar que su antepasado, Girion había conseguido hacer lo que todos creían que era una leyenda (conseguir arrancar una escama al dragón, lo que permitió a Bardo matarlo), y el cuerpo del dragón cayó sobre la balsa del Gobernador, quien estaba huyendo de la ciudad con todo el oro. Los sobrevivientes escogen a Bardo como su nuevo líder y buscan refugio en las ruinas de la ciudad de Valle. Kili confiesa su amor por Tauriel antes de partir con Fili, Oin y Bofur hacia la montaña para reencontrarse con la compañía, donde descubren que Thorin está afectado por el "mal del dragón", mientras busca desesperado la Piedra del Arca. Tras recordar palabras del dragón y recibir consejo de Balin, Bilbo, quien posee en secreto la Piedra del Arca, decide ocultarla de un demente Thorin, quien llega a desconfiar de sus propios compañeros.',
            'Mientras tanto, Galadriel rescata a Gandalf de Dol Guldur y lo entrega a Radagast, mientras Elrond y Saruman combaten a los espíritus de los Nazgûl. Sauron aparece e intenta tentar a Galadriel, pero esta con el poder de la luz de Earendil, logra expulsarlo de la fortaleza. El señor oscuro pierde su forma física pero su espíritu sobrevive y huye al este. Elrond cree que deben advertir a los montaraces de Gondor de vigilar las fronteras de Mordor, pero Saruman dice que sin el Anillo Único Sauron no es un problema y que se encargará de él en persona (lo que da razón pues se tentó ante el poder se Sauron). Gandalf le advierte a Radagast que legiones de orcos marchan hacia Erebor, y que avise a todas las aves y bestias de la batalla. Los orcos desean tomar la Montaña no por su riqueza, sino por su posición estratégica, pues en caso de tomarla, les abriría paso hacia el antiguo reino (Angmar). Pues si ese reino se alzara de nuevo, los Pueblos Libres correrían un gran peligro.',
            'El ejército de Azog se acerca a Erebor pero Bolgo le avisa que un ejército de elfos al mando de Thranduil también se acerca, por lo que Bolgo se dirige a Gundabad. Legolas y Tauriel son testigos de como Bolgo lidera un ejército de trasgos y murciélagos. Thranduil forja una alianza con Bardo con el objetivo de reclamar las gemas de Lasgalen, mientras que Bardo desea parte del tesoro para reconstruir Valle. El reclamo es justo, pero Thorin no desea compartir nada del tesoro. Gandalf llega a Valle y advierte a Thranduil sobre el ejército proveniente de Dol Guldur, pero el Rey Elfo no lo escucha. Bilbo huye de Erebor por la noche y les entrega la Piedra del Arca para que sirva de ayuda en la negociación.',
            'Al día siguiente, los ejércitos de Bardo y Thranduil sitian Erebor y piden parte del oro por la Piedra del Arca a Thorin. El enano, al conocer de la traición de Bilbo (que lo único que quiere es evitar la guerra y salvar a sus amigos enanos), está a punto de matarlo pero Gandalf lo persuade de dejarlo ir. Finalmente Thorin declina la oferta de paz, cuando llegan de las Colinas de Hierro un ejército de de su primo Dain Pie de Hierro (quien fue avisado de lo ocurrido por Röac, uno de los cuervos de la Montaña). Está a punto de estallar una batalla entre hombres, elfos y enanos cuando aparece el ejército de Azog por sorpresa. A pesar de que al principio parecía que los enanos iban a luchar solos contra los orcos, los elfos se unen a ellos, unidos por un enemigo común, haciendo que ambos bandos dejen a un lado sus diferencias por el futuro de la Tierra Media. Mientras, Thranduil, Bardo, Gandalf y Bilbo asisten a la defensa de Valle, pero los orcos los superan en número.',
            'Adentro de Erebor, Thorin se niega a unirse a la batalla, pero luego de una pesadilla en la que recuerda quién es realmente, logra liberarse del mal del dragón y lidera a la Compañía a la batalla. Dain y sus enanos de las Colinas de Hierro, a pesar de las enormes bajas sufridas y de su clara inferioridad numérica, cargan valerosamente ante la presencia de su rey para defender su hogar hasta el último aliento. Thorin y Dain se reúnen, en lo que Escudo de Roble decide acabar con los orcos, eliminando a su lider Azog. Por ello Thorin, Fili, Kili y Dwalin se dirigen a la Colina del Cuervo (donde está el puesto de mando de Azog) mientras el resto de la compañía ayuda al ejército de Dain. Tras saber que el ejército de Bolgo se dirige a la Colina del Cuervo, Bilbo decide ir a avisar a Thorin del peligro que corren, al mismo tiempo que Tauriel y Legolas se dirigen hacia allá.',
            'En la Colina del Cuervo, Azog captura y mata a Fili, y Kili se sacrifica para salvar a Tauriel de Bolgo. Bilbo recibe un golpe y queda inconsciente mientras Thorin lucha con Azog. Legolas logra matar a Bolgo y le devuelve la espada Orcrist a Thorin. Thorin logra matar a Azog, pero es mortalmente herido, mientras Radagast, Beorn y un ejército de Águilas llegan a la batalla, aniquilando al ejército orco proveniente de Gundabad.',
            'Bilbo despierta y se reencuentra con Thorin, quien le pide perdón al hobbit y hace las paces con él, antes de morir por sus heridas. Mientras Tauriel llora por la muerte de Kili, un desilusionado Legolas decide abandonar el reino del Bosque, y Thranduill le dice que marche al Norte con los Dúnedain y hable con un joven oficial (Aragorn). Tras un cortejo fúnebre en Valle, Bilbo se despide del resto de la Compañía y recuerda a Thorin no como una leyenda, sino como su amigo. Al regresar a la Comarca con Gandalf y antes de despedirse, el mago le confiesa que sabe del anillo mágico que encontró en los túneles de los trasgos, y pese a no conocer su verdadera naturaleza, le advierte que no debe usarlo a la ligera.',
            'Al llegar a Bolsón Cerrado, se encuentra con que los Sacovilla-Bolsón están subastando sus bienes porque asumieron que había muerto, y esclarece su identidad antes de entrar a su hogar.',
            'Sesenta años después, mientras recuerda su viaje en el día de su cumpleaños 111, Bilbo recibe alegremente la visita de su viejo amigo (Gandalf).'
        ]
    },
}
    
