let el_señor_de_los_anillos_la_comunidad_del_anillo_pelicula = {
    nombre: 'El Señor de los Anillos: La Comunidad del Anillo',
    ficha: {
        'Director': 'Peter Jackson',
        'Año de estreno': '2001',
        'Duración': '178 minutos',
        'Género': 'Aventuras y Fantasía épica'
    },
    image: 'images/peliculas/el_señor_de_los_anillos_la_comunidad_del_anillo_pelicula.jpg',
    indice: ['Argumento', 'Producción', 'Premios'],
    introducción: [
        'El Señor de los Anillos: La Comunidad del Anillo es una película de 2001 dirigida por Peter Jackson y tiene una duración total de 178 minutos (casi 3 horas). Se trata de la primera parte de la trilogía cinematográfica de El Señor de los Anillos, seguida por Las dos torres y El retorno del rey.',
        'La película cuenta las aventuras de la Comunidad del Anillo que aparecen en la novela homónima, que es la primera parte de la fantasía épica de J.R.R. Tolkien El Señor de los Anillos.'
    ],
    informacion: {
        'Argumento': [
            'En la Segunda Edad de la Tierra Media, los señores de los Elfos, los Enanos y los Hombres reciben anillos de poder. Sin saberlo, el Señor Oscuro Sauron forja el anillo Único en el Monte del Destino, infundiendo en él una gran parte de su poder para dominar, a través de él y a distancia, los otros Anillos, para que pueda conquistar la Tierra Media. Una alianza final de hombres y elfos lucha contra las fuerzas de Sauron en Mordor, donde el príncipe Isildur de Gondor corta el dedo de Sauron, y el Anillo con él, destruyendo así su forma física.',
            'Con la primera derrota de Sauron, comienza la Tercera Edad de la Tierra Media. Desafortunadamente, la influencia del Anillo corrompe a Isildur, y, en lugar de destruir el Anillo, Isildur lo toma para sí mismo. Isildur es luego asesinado por los Orcos, y el Anillo se pierde por 2500 años, hasta que es encontrado por Gollum, quien lo posee por cinco siglos. El anillo es encontrado por un hobbit llamado Bilbo Bolson.',
            'Sesenta años más tarde, Bilbo celebra su 111 cumpleaños en la Comarca, reuniéndose con su viejo amigo, Gandalf el Gris. Bilbo revela que tiene la intención de dejar la Comarca para una última aventura, y deja su herencia, incluido el Anillo, a su sobrino, Frodo. Aunque Bilbo ha comenzado a corromperse por el Anillo e intenta guardarlo para sí mismo, Gandalf interviene. Gandalf, sospechoso del Anillo, le dice a Frodo que lo mantenga en secreto y que lo mantenga a salvo. Gandalf luego investiga el Anillo, descubre su verdadera identidad y vuelve a avisar a Frodo. Gandalf también se entera de que Gollum fue torturado por los orcos y que Gollum pronunció dos palabras durante su tortura: "Comarca" y "Bolson". Gandalf instruye a Frodo para que abandone la Comarca, acompañado por su jardinero Samsagaz Gamyi.',
            'Gandalf viaja a Isengard para reunirse con su hechicero Saruman el Blanco, pero se entera de que se ha unido a Sauron, quien ha enviado a los nueve Nazgûl para encontrar a Frodo. Después de una breve batalla, Saruman vence y encarcela a Gandalf. Frodo y Sam se unen a sus compañeros hobbits, Merry y Pippin, y evaden a los Nazgûl, llegando a Bree, donde están destinados a encontrarse con Gandalf. Sin embargo, Gandalf nunca llega, y en su lugar son ayudados por un guardabosques llamado Trancos, un amigo de Gandalf, que los acompaña a Rivendell.',
            'Los hobbits sufren una emboscada de los Nazgûl en Weathertop, cuyo líder, el Rey Brujo, apuñala a Frodo con una espada Morgul maldita. Arwen, una elfo, y Trancos acuden en ayuda de Frodo, lo rescatan e incapacitan a los nazgûl. Ella lo lleva a Rivendell para curarlo. Frodo se encuentra con Gandalf, quien escapó de Isengard con la ayuda de Gwaihir, un águila gigante, y con Bilbo, que se fue a Rivendell como parte de su última aventura. El padre de Arwen, Lord Elrond, convoca un consejo donde se decide destruir el Anillo en el Monte del Destino. Mientras los participantes discuten, Frodo se ofrece como voluntario para llevar el Anillo, acompañado por Gandalf, Sam, Merry, Pippin, el elfo Legolas, el enano Gimli, Boromir de Gondor y Trancos, quien se revela como Aragorn, el heredero de Isildur y el legítimo rey de Gondor. Bilbo, que sufre por la responsabilidad que ha asumido Frodo por sus acciones, le da a Frodo su espada, “Dardo”. La Comunidad del Anillo comienza, pero la magia de Saruman los obliga a viajar a través de las Minas de Moria, para gran disgusto de Gandalf.',
            'Tras descubrir que los enanos de Moria han sido asesinados, la Comunidad sufre el ataque de los orcos y un troll de cueva. Logran derrotarlos, pero se enfrentan al Daño de Durin, un balrog que reside dentro de las minas. Gandalf lo hace caer a un vasto abismo, pero el balrog arrastra a Gandalf a la oscuridad con él. El resto de la Comunidad, ahora dirigida por Aragorn, llega a Lothlórien, hogar de los elfos Galadriel y Celeborn. Galadriel le informa a Frodo en privado que solo él puede completar la búsqueda y que uno de sus amigos intentará tomar el Anillo. Mientras tanto, Saruman crea un ejército de Uruk-hai para rastrear y matar a la Comunidad.',
            'La Comunidad abandona Lothlórien por el río a Parth Galen. Frodo se aleja y Boromir intenta quitarle el Anillo con desesperación pero luego, aunque decepcionado de sí mismo, logra recuperarse y volver a ser aliado del hobbit. Temiendo que el anillo corrompa así sus demás amigos, Frodo decide viajar solo a Mordor y casi en simultáneo La Comunidad es emboscada por los Uruk-hai. Merry y Pippin son llevados cautivos, y Boromir, luego de actos heroicos, es herido de muerte por el jefe de los Uruk, Lurtz. Aragorn llega y mata a Lurtz, y observa a Boromir redimido morir en paz. Sam sigue a Frodo y lo acompaña para continuar con su promesa a Gandalf de proteger a Frodo, mientras que Aragorn, Legolas y Gimli van a rescatar a Merry y Pippin.'
        ],

        'Producción': [
            '<h2>Diseño</h2>',
            'El diseño de producción comenzó mientras Peter Jackson, Fran Walsh y Philippa Boyens se encargaban de escribir el guion, ya que no era necesario esperar a que este estuviera terminado gracias a las descripciones ofrecidas por la novela. Desde un principio Jackson dejó claro al equipo de diseñadores de Weta Workshop que no quería "cine fantástico estilo Hollywood", sino autenticidad. El trabajo que los artistas Alan Lee y John Howe habían realizado durante años ilustrando las obras de J. R. R. Tolkien fue el que más le gustó a Jackson, tanto que mientras escribía el guion tenía colgados sus dibujos en la pared para que le sirvieran de inspiración. Ambos aceptaron la oferta del director para participar en la trilogía como artistas conceptuales y se unieron a los trabajadores de Weta en su estudio de Nueva Zelanda.',
            'Procuraron darle un diseño distintivo a cada raza que aparece en la novela, tanto en su vestimenta como en su armamento o arquitectura, estableciendo diseños simbólicos. Además trataron de insinuar "una noción de historia del arte" porque, dentro de la ficción, la Tierra Media había sido construida en gran parte por los númenóreanos, una raza de hombres casi extinguida en la época en la que transcurre la película, y aún quedaban vestigios de ella.',
            '<h2>Efectos visuales</h2>',
            'Weta Digital, empresa creada por Peter Jackson con base en Wellington (Nueva Zelanda) fue la encargada de añadir los efectos visuales. La mayor parte de las tomas ambientales de la trilogía tiene algún tipo de manipulación digital.',
            'El troll de las cavernas que aparece en Moria fue la primera criatura que esculpió el diseñador Richard Taylor y la primera en ser escaneada para su creación digital. Tras construir su esqueleto y sus músculos por ordenador, los diseñadores de Weta Digital incorporaron la piel escaneada y realizaron una animación de prueba con varios movimientos del troll y una pelota con el fin de mostrar los resultados a New Line. Para planificar la escena donde el troll ataca a la Compañía del Anillo en la tumba de Balin, los diseñadores construyeron digitalmente una copia exacta del plató donde se iba a rodar y le incorporaron a los nueve personajes y al troll, todos ellos con movimientos capturados. Usando esta misma técnica, los diseñadores incorporaron unos electrodos a un tronco para que simulara una cámara y Peter Jackson, usando unas gafas de realidad virtual para ver el plató digital que había sido realizado por ordenador, filmó la escena que le serviría de guía para el rodaje como si el troll estuviera en un plató real.',
            'Steven Regelous, uno de los trabajadores de Weta, diseñó el software MASSIVE para facilitar la materialización por pantalla de las grandes huestes militares que aparecen en el prólogo de La Comunidad del Anillo; capaz de crear miles de individuos por ordenador, el software les otorga además una inteligencia artificial que permite añadirles conductas individuales y dotarles de movimiento.',
            '<h2>Banda sonora</h2>',
            'La banda sonora original de La Comunidad del Anillo fue lanzada el 20 de noviembre de 2001. Al contrario que los posteriores álbumes de un solo disco, su canción inicial no contiene el motivo de la "Historia del Anillo". Los creadores pretendían grabar una secuencia de prólogo más corta (acompañada con el tema "The Prophecy"), pero la idea fue desechada finalmente en favor de una escena más detallada y atractiva. La carátula frontal de este disco estaba disponible en varios diseños.'
        ],
        'Premios': [
            '<h2>Premios Óscar</h2>',
            'La Comunidad del Anillo fue nominada a trece premios Óscar, de los cuales ganó cuatro: mejor fotografía, mejor maquillaje, mejor banda sonora y mejores efectos visuales. Las otras nueve nominaciones fueron a mejor película, mejor director, mejor guion adaptado, mejor canción original, mejor dirección artística, mejor diseño de vestuario, mejor montaje, mejor sonido y mejor montaje de sonido.',
            '<h2>Premios BAFTA</h2>',
            'La Comunidad del Anillo fue nominada a doce premios BAFTA, de los cuales ganó dos: mejor maquillaje y mejor diseño de producción. Las otras diez nominaciones fueron a mejor película, mejor director, mejor guion adaptado, mejor fotografía, mejor montaje, mejor sonido, mejores efectos visuales, mejor banda sonora, mejor diseño de vestuario y mejor maquillaje y peluquería.',
            '<h2>Premios Globo de Oro</h2>',
            'La Comunidad del Anillo fue nominada a cuatro premios Globo de Oro, de los cuales ganó dos: mejor película - drama y mejor director. Las otras dos nominaciones fueron a mejor banda sonora y mejor canción original.',
            '<h2>Premios del Sindicato de Actores</h2>',
            'La Comunidad del Anillo fue nominada a tres premios del Sindicato de Actores, de los cuales ganó uno: mejor reparto. Las otras dos nominaciones fueron a mejor actor de reparto y mejor actriz de reparto.',
            '<h2>Premios Saturn</h2>',
            'La Comunidad del Anillo fue nominada a diez premios Saturn, de los cuales ganó nueve: mejor película de fantasía, mejor director, mejor guion, mejor actor, mejor actriz de reparto, mejor música, mejor vestuario, mejor maquillaje y mejores efectos especiales. La otra nominación fue a mejor actor de reparto.',
            '<h2>Premios MTV Movie</h2>',
            'La Comunidad del Anillo fue nominada a seis premios MTV Movie, de los cuales ganó cinco: mejor película, mejor actor, mejor villano, mejor lucha y mejor actuación revelación. La otra nominación fue a mejor beso.',
            '<h2>Premios Grammy</h2>',
            'La Comunidad del Anillo fue nominada a tres premios Grammy, de los cuales ganó dos: mejor banda sonora y mejor canción escrita para una película, televisión u otro medio visual. La otra nominación fue a mejor álbum instrumental de banda sonora para una película, televisión u otro medio visual.',
            '<h2>Premios Hugo</h2>',
            'La Comunidad del Anillo fue nominada a dos premios Hugo, de los cuales ganó uno: mejor presentación dramática. La otra nominación fue a mejor representación dramática - forma larga.',
            '<h2>Premios Satellite</h2>',
            'La Comunidad del Anillo fue nominada a diez premios Satellite, de los cuales ganó siete: mejor película - drama, mejor director, mejor guion adaptado, mejor fotografía, mejor montaje, mejor banda sonora y mejores efectos visuales. Las otras tres nominaciones fueron a mejor actor, mejor diseño de vestuario y mejor sonido.',
            '<h2>Premios Empire</h2>',
            'La Comunidad del Anillo fue nominada a seis premios Empire, de los cuales ganó tres: mejor película británica, mejor director británico y mejor actor británico. Las otras tres nominaciones fueron a mejor película, mejor actor y mejor actriz.',
            '<h2>Premios AFI</h2>',
            'La Comunidad del Anillo fue nominada a diez premios AFI, de los cuales ganó uno: película del año. Las otras nueve nominaciones fueron a director del año, actor del año, actriz del año, actor de reparto del año, actriz de reparto del año, guion del año, fotografía del año, diseño de producción del año y edición del año.',

        ]
    }

}
        

let el_señor_de_los_anillos_las_dos_torres_pelicula = {
    nombre: 'El Señor de los Anillos: Las dos torres',
    ficha: {
        'Director': 'Peter Jackson',
        'Año de estreno': '2002',
        'Duración': '179 minutos',
        'Género': 'Fantasía'
    },
    image: 'images/peliculas/el_senor_de_los_anillos_las_dos_torres_pelicula.jpg',
    indice: ['Argumento', 'Producción', 'Premios'],
    introducción:[
        'El Señor de los Anillos: Las Dos Torres (2002) es la segunda película de la trilogía cinematográfica de El Señor de los Anillos. Fue dirigida por Peter Jackson con una duración total de 180 minutos (3 horas).'
    ],
    informacion: {
        'Argumento': [
            'Tras internarse en Emyn Muil, Frodo Bolsón y Sam Gamyi se encuentran con la criatura Gollum, que intenta quitarles el Anillo por la fuerza pero, al verse vencido, promete a los hobbits guiarlos hasta Mordor. Tras sacarlos de Emyn Muil y atravesar la Ciénaga de los Muertos, llegan al Morannon, la «Puerta Negra» de Mordor. No obstante, la gran protección que tiene les imposibilita entrar por ahí y Gollum les propone tomar el camino secreto de Cirith Ungol. Durante el viaje, se encuentran con una tropa avanzada de montaraces de Gondor dirigida por Faramir, hijo del senescal de Gondor y hermano de Boromir, quien los toma como prisioneros y descubre que portan el Anillo Único. Faramir cuenta a los hobbits que Boromir ha muerto y que fue encontrado en un bote élfico. Esto hace pensar a Frodo, pues creía que Boromir solo quería el Anillo, y por su hermano descubre que murió protegiendo a la Compañía, tal y como habían jurado todos sus miembros al salir de Rivendel. Faramir decidió llevarlos ante su padre, pero, a su paso por la derruida ciudad de Osgiliath, los soldados gondorianos se encuentran combatiendo a las fuerzas de Sauron conducidas por algunos Nazgûl. Al darse cuenta del maligno poder del Anillo sobre Frodo, al que casi captura uno de los Nazgûl, Faramir decide liberarlos para que completen su misión.',
            'Mientras tanto, los uruk-hai que llevan prisioneros a Merry Brandigamo y Pippin Tuk son abatidos por los jinetes de Rohan exiliados y los hobbits consiguen escapar de la batalla, internándose en el bosque de Fangorn. Aragorn, Legolas y Gimli, que habían ido tras ellos, se encuentran con los restos de la batalla y siguen las huellas de sus amigos hasta el interior del bosque. En él se reencuentran con Gandalf, al que creían muerto tras su caída por el puente de Moria, y una vez les informa de que ha dejado a Merry y Pippin en buenas manos, se dirigen juntos a Edoras, capital de Rohan, para hablar con el rey Théoden. Sin embargo, este se encuentra hechizado por Saruman gracias a la ayuda del consejero del rey, Gríma, que trabaja en secreto para el mago. Bajo su influjo, desterró a su sobrino Éomer tras la muerte de Théodred, su hijo y heredero al trono. Gandalf logra liberarle y Théoden decide refugiar a su pueblo en la fortaleza del Abismo de Helm con el fin de no arriesgarse a un conflicto abierto con Isengard en Edoras.',
            'Saruman envía a un ejército gigantesco de uruk-hai a destruir el Abismo de Helm, mientras Gandalf va en busca de los rohirrim exiliados para la batalla. El elfo Haldir, del bosque de Lothlórien, acude con un pequeño ejército de galadhrim en ayuda de Rohan y juntos consiguen resistir hasta la llegada de Gandalf, Éomer y numerosos rohirrim, que derrotan a los uruks.',
            'Mientras tanto, Pippin y Merry, que habían sido confiados por Gandalf al ent Bárbol, acuden junto con él a un concilio entre varios miembros de su raza en el que estos decidirían qué hacer respecto a la guerra. Tras largo tiempo dialogando, deciden que no es asunto suyo. No obstante, cuando Bárbol lleva a los hobbits fuera del bosque, descubre que Saruman ha talado muchos árboles y con su grito atrae de nuevo a todos los ents, que marchan hacia Isengard y la destruyen.',
            'Tras estas victorias, Gandalf y el resto creen que ha llegado la hora de librar la batalla final, que se decidirá en Gondor y donde todos jugarán sus últimas cartas por el futuro de la Tierra Media.'
        ],
        'Producción': [
            'Las películas que componen la trilogía de El Señor de los Anillos fueron rodadas exclusivamente en Nueva Zelanda y al mismo tiempo, empleando un total de catorce meses desde octubre del año 1999 a diciembre del año 2000. El reparto trabajaba durante seis días a la semana, con jornadas de trabajo que duraban entre doce y catorce horas. Para Las dos torres organizaron tres equipos de rodaje, ya que la película se divide en tres líneas argumentales. Debido a que solo había un director, cada equipo disponía de un sistema vía satélite con el que Jackson podía supervisar todo el trabajo al mismo tiempo.',
            'Las escenas que recrean los acontecimientos en Emyn Muil con Frodo, Sam y Gollum, se rodaron en el parque nacional de Tongariro, más concretamente en el volcán Ruapehu, en una pista de esquí llamada Whakapapa. No obstante, la falta de algunos planos necesarios para la película y que no se encontraban en el lugar, obligó al equipo a recrearlo en un plató.',
            'En la novela, las llanuras de Rohan, donde tiene lugar la persecución de los uruks por parte de Aragorn, Legolas y Gimli, son descritas como grandes praderas. Sin embargo, debido a que en Nueva Zelanda no hay praderas, el equipo acabó usando la reserva de Poolburn, en Otago. Durante el rodaje, los tres actores principales se lesionaron: Viggo Mortensen se rompió los dedos del pie al dar una patada a un casco de uruk, Orlando Bloom se fracturó una costilla al caerse de su caballo, y Brett Beattie, doble de Gimli, se dislocó la rodilla. En el aparcamiento de los estudios Stone Street de Wellington, se construyó una rambla con el mismo aspecto que el paisaje de Poolburn para rodar algunas tomas extras de uruks hablando, aunque finalmente fueron rodadas allí todas las escenas que había en primer plano.  En el lago Poolburn, se construyó la aldea del Folde Oeste que es atacada y destruida por los uruks. En el cerro de Deer Park Heights, a las afueras de la ciudad de Queenstown, se grabó la marcha de los habitantes de Edoras hacia el Abismo de Helm, entre octubre y noviembre del año 2000 y con la colaboración de un total de 200 extras.',
            'Los lindes de Fangorn, donde los rohirrim atacan a los uruks, fueron rodados en los lagos Mavora, mientras que para las escenas en el interior del bosque, al no encontrar nada adecuado, usaron un plató con árboles fabricados por Weta Workshop y cuyo suelo fue hecho a base de 400 sacos de hojas.',
            'Para la Ciénaga de los Muertos, el equipo pensó en usar los grandes pantanos situados a las afueras de Te Anau, en Kepler Mire, que con el paso de miles de años habían sido cubiertos por musgo, formando sobre el agua superficies que parecían tierra firme. Sin embargo, debido a que el terreno no era del todo sólido, abandonaron la idea de grabar allí y recrearon el cenagal en tres platós: uno interior y dos exteriores, siendo uno más grande que el otro. El plató interior sirvió para grabar las escenas nocturnas, mientras que en el exterior grande fueron rodadas el resto a excepción de las que incluían los cadáveres bajo el agua, filmadas en el pequeño. Por otro lado, el equipo grabó algunas vistas aéreas en helicóptero del lago Tawharekiri, para usarlas como tomas amplias en la película.',
            'Las escenas de Ithilien, con el ataque de los montaraces a los haradrim y la captura de Frodo y Sam, fueron filmadas en Twelve Mile Delta, a las afueras de la ciudad de Queenstown. Entre otras de las escenas que fueron rodadas en plató están: la de la Puerta Negra y la de Henneth Annûn y el Estanque Vedado. El rodaje de Osgiliath fue hecho en un escenario construido en partes con croma detrás para añadir el fondo a ordenador.',
            'Edoras fue rodado en el monte Sunday (Canterbury), en un gran escenario que tardó ocho meses en construirse y para cuyas escenas fueron contratados alrededor de 200 extras y 100 caballos. El interior del castillo de Meduseld, que combina el estilo vikingo con el tailandés, fue construido en un plató de Wellington, a pesar de que el exterior se encontraba también en los decorados del monte Sunday.',
            'El Abismo de Helm fue rodado en la cantera Dry Creek Quarry, en Lower Hutt. Los propietarios de ésta se la cedieron al equipo de la película durante un año para que construyeran los escenarios y grabaran las escenas. Para el rodaje fueron empleados un total de cuatro meses, tres de ellos filmando de noche. Los actores y numerosos extras que intervinieron, sufrieron muchas penalidades y afirmaron que fue muy duro por las pocas horas de sueño, el peso de las armaduras y la lluvia artificial. Viggo Mortensen acabó con los nudillos y un diente roto y Bernard Hill fue golpeado en una ocasión por otro actor con su espada, recibiendo tres puntos en la oreja.',
            '<h2>Diseño de vestuario</h2>',
            'Cuando el equipo de diseñadores de Weta Workshop comenzó a esbozar las primeras armaduras para las películas, no tenían demasiados conocimientos sobre el tema y carecían de un experto que les pudiera orientar. Por ello, los primeros diseños eran poco reales, aunque ya comenzaron a aparecer aspectos que se mantendrían en las armaduras definitivas. Con la incorporación al equipo de Alan Lee y John Howe, experto en armaduras, los diseños comenzaron a tomar forma.',
            'En Las dos torres se introducen muchas razas y pueblos nuevos. Peter Jackson y Richard Taylor establecieron que el ejército de los uruk-hai fuera el primero en diseñarse. Los esbozos iniciales, incluían escudos de madera y armaduras con tachones, que fueron descartadas tras la incorporación de Alan Lee y John Howe. Para facilitar el movimiento, el diseño final ofrecía una mayor protección de la parte superior que de las piernas. Se incorporó un casco que les tapaba los ojos casi por completo, teniendo tan solo una pequeña ranura, con el fin de que los uruks parecieran más aterradores; además, para que el ejército tuviera una organización mayor que la de los orcos y para que todos los uruks no fueran iguales, los diseñadores establecieron distintas especialidades, diferenciadas principalmente por el casco: el de los fanáticos o berserkers lleva una cresta de capitán en la parte superior, el de los espadachines tiene pinchos en la parte delantera para atacar a su contrincante, la ranura del de los lanceros les obliga a mirar hacia arriba y agacharse para luchar, y el de los zapadores tiene un escudo que cubre la nuca para protegerles de las rocas que cayeran tras la explosión del muro de Cuernavilla.',
            'La armadura del ejército élfico que llega al Abismo del Helm fue diseñada para los elfos de la Última Alianza que aparecen en el prólogo de La Comunidad del Anillo. Si bien los trajes élficos son muy sueltos, las armaduras que diseñaron eran muy ajustadas para facilitar la lucha. Las formas de la armadura final se inspiran en el Art Nouveau, sin líneas rectas y con motivos de plantas. Los elfos llevaban unas 6 o 7 capas de vestimenta, entre armadura y ropajes, lo que obligaba a los actores a mantener una posición erguida. Daniel Falconer se encargó de dar colorido a la vestimenta, usando colores otoñales como el bronce, el rojo o el marrón, en contraste con los colores más primaverales que llevaba la del prólogo, para reflejar la decadencia de los elfos en la Tierra Media.',
            'El diseño de los rohirrim está basado en su mayoría en los pueblos nórdicos, especialmente en los vikingos. Para su concepción, los trabajadores de Weta usaron sobre todo cuero y telas, y añadieron numerosos motivos ecuestres, tanto en la vestimenta como en las armas. Hicieron 250 vestimentas de rohirrim, cuyo estilo era global, pero con algunas diferencias, ya que Rohan es un pueblo disperso, formado por granjeros y pastores que son convocados para luchar y no forman un ejército unificado como Gondor. Por el contrario, la Guardia Real de Edoras si lleva el mismo traje, similar a los del resto de rohirrim, pero algo más elaborado y con otros elementos, como la cola de caballo colgando de la parte superior del casco.',
            'Los primeros diseños para los haradrim estaban basados en la cultura de Papúa Nueva Guinea, mezclados con elementos africanos, pero con el objetivo de que su vestimenta no se pareciera a la de ninguna cultura, los diseñadores fueron incluyendo nuevos elementos.',
            '<h2>Efectos visuales</h2>',
            'La empresa Weta Digital fue la encargada de añadir los efectos visuales a las tres películas. Al igual que ocurrió con el guion, los trabajadores de Weta admitieron que Las dos torres supuso mayor dificultad que La Comunidad del Anillo debido al mayor número de tomas y a la aparición de personajes digitales nuevos, como Bárbol y Gollum.',
            'Para facilitar la materialización por pantalla de las grandes huestes militares que aparecen en la película, Steven Regelous, uno de los trabajadores de Weta, diseñó el software Massive. Este programa es capaz de crear miles de criaturas por ordenador a las que además otorga una inteligencia artificial para añadir conductas individuales y dotar de movimiento a los individuos. Por otra parte, John Allitt desarrolló un software conocido como Creador de Orcos, que era capaz de crear uruk-hai de distintas características físicas para que fueran generados por Massive, de forma que este establece unos parámetros aleatorios para que ningún uruk sea igual.',
            'En un principio el equipo de animación pensó en usar dos técnicas para elaborar al personaje de Gollum: la captura de movimientos y la manipulación de marionetas (keyframe). El equipo de rodaje había grabado dos tomas de cada escena en la que aparecía Gollum, una con el actor Andy Serkis como referencia para el resto de actores y otra sin él para que los animadores pudieran introducir más tarde al Gollum digital. Sin embargo, cuando el equipo de Weta vio las tomas, observaron que los actores interpretaban mejor en las que aparecía Serkis, así que decidieron usar la técnica del rotoscopio para Gollum, ya que permite crear un personaje digital siguiendo una referencia filmada en vivo.',
            'Debido a la dificultad que suponía articular el rostro de la marioneta de Bárbol, el equipo de Weta usó fondos de acción para cambiar la cara por otra digital. Para ello, realizaron un escáner de la cabeza de la marioneta y crearon un mecanismo de animación facial similar al que usaron con Gollum. El resto de ents fueron creados a partir de nueve diseños de Alan Lee, a los que Weta hizo algunas modificaciones para formar numerosos ents distintos.',
            '<h2>Sonido</h2>',
            'El equipo de sonido estaba formado por el diseñador David Farmer, bajo la supervisión de los editores Ethan Van der Rijn y Mike Hopkins, y los mezcladores Christopher Boyes, Michael Semanick, Michael Hedges entre otros. La mezcla del sonido no finalizó hasta el 27 de octubre de 2002, dos meses antes del estreno de la película. Si bien su base de trabajo se encontraba en Wellington, el equipo tuvo que buscar un lugar fuera de la ciudad debido a lo ruidosa que era. Encontraron un cementerio a las afueras y allí grabaron diversos sonidos, como el vuelo e impacto de las flechas, siempre de noche para evitar todos los ruidos ambientales posibles.',
            'Debido a que disponían de la biblioteca de La Comunidad del Anillo, pudieron centrarse en los nuevos sonidos que necesitaba la segunda parte y en mejorar los que ya tenía la primera.',
            'Para grabar un sonido que imitara a una multitud de 10 000 uruk-hai, el equipo acudió al estadio Westpac de Wellington, donde se estaba disputando un partido de cricket, y Peter Jackson pidió al público que pataleara y gritara algunas frases en la lengua negra que eran proyectadas en la pantalla gigante para que pudieran leerlas. Para recrear el sonido emitido por las bestias aladas de los Nazgûl, usaron un gruñido de burro y para los huargos tuvieron que imitar los ladridos de un perro. La voz del Anillo fue puesta por Janet Roddick, una experta en música ambiental, usando diferentes formas según el personaje al que se dirigía.',
            'Con el objetivo de que el público que no había leído la novela dudara sobre la identidad del mago que aparecía en el bosque de Fangorn ante Aragorn, Legolas y Gimli, el equipo de sonido mezcló la voz de Ian McKellen (Gandalf) con la Christopher Lee (Saruman). Para la voz del ent Bárbol, de la que se ocupaba John Rhys-Davies, el actor que también interpreta a Gimli, construyeron una caja de madera de dos metros de alto, a la que acoplaron bafles dentro. En primer lugar, grabaron la voz del actor y la emitieron desde un lado de la caja para volver a grabarla desde el otro; de esta forma, la voz resultante tenía una resonancia de madera.',
            '<h2>Música</h2>',
            'El músico Howard Shore fue el encargado de componer, dirigir y orquestar la banda sonora para las tres películas de El Señor de los Anillos. Las partituras fueron interpretadas por la Orquesta Filarmónica de Londres en el ayuntamiento de la ciudad de Watford (Hertfordshire, Reino Unido), mientras que la mezcla y edición se hizo en los estudios Abbey Road de Londres. Además, Peter Jackson quiso participar de algún modo en la banda sonora, así que Shore dejó que tocara el gong.',
            'En Las dos torres, tan solo fueron reutilizados unos diez minutos de música de La Comunidad del Anillo. Por ejemplo, en el tema de Gollum, Shore incluyó fragmentos del que se escucha durante el prólogo de La Comunidad del Anillo, pues ambos mantenían una relación con la historia del Anillo. A su vez, dicho tema tiene una parte más relajada y melancólica que refleja la personalidad buena de Gollum, mientras que la otra parte, que refleja la personalidad malvada, es más "esquizofrénica" en palabras del compositor. En el tema del Abismo de Helm, Shore mezcló varias ideas temáticas en función del ejército que aparecía y en el caso de los elfos, utiliza el tema de Lothlórien que aparece en la primera película, pero con más ritmo.',
            'Las guionistas Fran Walsh y Philippa Boyens también compusieron algunas canciones basadas en las escenas, que fueron traducidas a anglosajón y sindarin por David Salo, un experto en las lenguas de J. R. R. Tolkien. La soprano Isabel Bayrakdarian, Sheila Chandra y Elisabeth Frase fueron las encargadas de interpretar algunas de estas canciones. Otras sesenta piezas vocales fueron interpretadas por un coro femenino de Londres, dirigido por Terry Edwards. El Brompton Oratory Choir, que ha participado en muchas otras películas, como la saga de Harry Potter, se encargó del tema conocido como La marcha de los Ents. La canción de Gollum, compuesta solamente por Fran Walsh, fue interpretada por la italo-islandesa Emilíana Torrini. Además, Shore compuso música nueva para la versión extendida de la película, como el tema de Gondor, que serviría más tarde para El retorno del Rey.',
            '<h2>Banda sonora</h2>',
            'La banda sonora de Las dos torres fue lanzada el 2 de diciembre de 2002. Tiene una duración de 73 minutos y fue distribuida por Reprise Records. Además de la edición normal y la especial, se puso a la venta en Internet otra versión limitada, presentada en una caja de imitación de piel en color marrón, y con algunos extras más como mapas de la Tierra Media y un tráiler en exclusiva de la tercera película de la trilogía, El retorno del Rey.'

        ],
        'Premios': [
            '<h2>Premios Óscar</h2>',
            'La película fue nominada a seis premios Óscar, incluyendo mejor película, mejor dirección de arte, mejor sonido, mejor montaje, mejor efectos visuales y mejor mezcla de sonido. Ganó en las dos últimas categorías.',
            '<h2>Premios BAFTA</h2>',
            'La película fue nominada a seis premios BAFTA, incluyendo mejor película, mejor director, mejor guion adaptado, mejor fotografía, mejores efectos visuales y mejor maquillaje y peluquería. Ganó en las dos últimas categorías.',
            '<h2>Premios del Sindicato de Actores</h2>',
            'La película fue nominada a tres premios del Sindicato de Actores, incluyendo mejor reparto, mejor actor de reparto (Ian McKellen) y mejor actriz de reparto (Miranda Otto). Ganó en las dos últimas categorías.',
            '<h2>Premios Saturn</h2>',
            'La película fue nominada a diez premios Saturn, incluyendo mejor película de fantasía, mejor director, mejor guion, mejor actor (Viggo Mortensen), mejor actor de reparto (Andy Serkis), mejor actriz de reparto (Miranda Otto), mejor vestuario, mejor maquillaje, mejores efectos especiales y mejor banda sonora. Ganó en las tres últimas categorías.',
            '<h2>Premios MTV Movie</h2>',
            'La película fue nominada a tres premios MTV Movie, incluyendo mejor película, mejor actor (Viggo Mortensen) y mejor actuación virtual (Andy Serkis). Ganó en las dos últimas categorías.',
            '<h2>Premios Grammy</h2>',
            'La película fue nominada a dos premios Grammy, incluyendo mejor banda sonora y mejor canción compuesta para una película, televisión u otro medio visual (Gollum\'s Song). Ganó en la primera categoría.',
        ]
    },
}


let el_señor_de_los_anillos_el_retorno_del_rey_pelicula = {
    nombre: 'El Señor de los Anillos: El Retorno del Rey',
    ficha: {
        'Director': 'Peter Jackson',
        'Año de estreno': '2003',
        'Duración': '201 minutos',
        'Género': 'Fantasía'
    },
    image: 'images/peliculas/el_señor_de_los_anillos_el_retorno_del_rey_pelicula.jpg',
    indice:['Argumento', 'Producción', 'Premios'],
    introducción:[
        'El Señor de los Anillos: El Retorno del Rey es la tercera parte de la Trilogía Cinematográfica de El Señor de los Anillos, y adaptación del libro de mismo nombre.',
        'Esta película cuenta el final de la misión del Portador del Anillo y el momento climático de la Guerra del Anillo, con el ataque de Sauron sobre Gondor.',
        'El Retorno del Rey es considerada una de las mejores películas de la historia del cine. Se trata de la cinta con mayor número de Premios Óscar de toda la historia, empatada en número de estatuillas con Ben-hur y Titanic, las tres con 11 Premios. Llegó a ser la segunda película más taquillera de la historia, solo por detrás de Titanic, hasta que Avatar (2009) le quitó este privilegio. Recientemente, también ha sido superada en recaudación en taquilla por Harry Potter y las Reliquias de la Muerte - Parte 2, y por Transformers: El Lado Oscuro de la Luna.'

    ],
    informacion:{
        'Argumento': [
            'La historia comienza con un recuerdo de cómo el hobbit Smeágol llegó a poseer el Anillo de Poder, tras matar a su amigo Déagol, quien lo había encontrado en el fondo de un río (donde cayó muchos años antes, como se vio en la primera película, cuando unos orcos asesinaron a Isildur, quien había cortado el dedo a Sauron en el Sitio de Barad-dûr, que concluyó la Guerra de la Última Alianza, y había conservado el Anillo a pesar de las advertencias de Elrond). A partir de entonces continúa el relato en donde se dejó mientras Gollum lleva a Frodo y Sam a través de la entrada cercana a Minas Morgul, en donde ven a sus ejércitos partir a la guerra.',
            'Luego de la victoria en la batalla del Abismo de Helm, el Rey de Rohan, junto a Gandalf, Aragorn, Legolas, Gimli y Éomer se dirigieron hacia Isengard, la ciudadela de Saruman desde la que había partido el ataque. La encontraron completamente destruida por los Ents, y volvieron a reencontrarse con Merry y Pippin. Entre las ruinas de la ciudad, Pippin encontró el palantir de Saruman, que Gandalf rápidamente tomó bajo su custodia (en la versión extendida DVD, hay una escena eliminada donde se muestra a Saruman y a Grima. Gandalf rompe la vara de Saruman y el rey Théoden invita a Grima a regresar a Rohan. Saruman se burla de Grima, y este, lleno de ira, coge una daga que tenía escondida y lo apuñala. Legolas lanza una flecha que impacta a Grima y ambos mueren. Saruman cae desde la terraza de la torre y cuando llega al suelo suelta el Palantir que tenía escondido. Luego Pippin lo encuentra).',
            'Después de las celebraciones de la victoria, Pippin tuvo gran curiosidad por ver de nuevo la piedra, y se la quita a Gandalf mientras dormía. Vio en ella el ojo de Sauron, quien intentó obtener información de él, aunque Gandalf logró intervenir rápidamente, sin que Pippin revelara nada sustancial. Pippin, en cambio, sí llegó a ver algo importante: un árbol blanco. El mago entendió que se trataba del Árbol Blanco de Minas Tirith, lo cual quería decir que Sauron planeaba atacar Minas Tirith. Gandalf partió inmediatamente a advertirles, y llevándose también a Pippin para protegerlo en la ciudad. Pero al llegar se encuentran al Senescal Denethor II apenado por la muerte de su hijo preferido, Boromir, y completamente indiferente a todo lo demás. Sintiéndose en parte responsable, ya que Boromir murió defendiéndolo, Pippin ofrece sus servicios a Denethor como soldado. Denethor desconfía de Gandalf sabiendo Aragorn acompaña al Rey Théoden, quien deberá recuperar su trono como heredero de Isildur, lo que significaría el derrocamiento de Denethor, quien le reprocha a Gandalf que quiera usarlo de escudo contra el ataque de Mordor, para que luego Aragorn ocupe el trono. Por todo esto Denethor se niega a seguir la recomendación de Gandalf acerca de pedir auxilio de Rohan, pero Gandalf decide invocar la ayuda de Rohan y manda a Pippin a encender las almenaras de Minas Tirith. Aragorn al advertir la petición de ayuda la comunica a Théoden, quien a pesar de haber dudado en intervenir (ya que Gondor no le auxilió en la Batalla del Abismo de Helm ni en otros ataques de Saruman), al final decide reunir a su ejército para marchar a la guerra, y pide a Gamling y a Éomer que lleven a todos los hombres posibles al Baluarte del Sagrario.',
            'Las fuerzas de Rohan se toman unos días para reunir a sus jinetes, para luego partir hacia Minas Tirith; Théoden se lamenta al ver que no todos sus súbditos acuden al llamado y que no contará con fuerzas suficientes para derrotar a Mordor, entonces Gamling le reprocha que no lograrán regresar con la victoria, pero Théoden le dice a él y a otros hombres que eso no importa, lo que importa es enfrentarlos en batalla a pesar de que sean derrotados, así decide proseguir la marcha. Aragorn recibe una misteriosa visita de Elrond: su hija Arwen vio en un futuro que podría tener hijos con Aragorn y eso la decidió a quedarse en la Tierra Media, por lo que Elrond brindó su ayuda en la guerra reforjando la gran espada Narsil que había derrotado a Sauron en su momento (los fragmentos de la espada que se conservaron por siglos en Rivendel, fueron reforjados en una nueva espada con el nombre de Andúril, Llama del Oeste), y recordándole a Aragorn que con esa arma conseguiría la cooperación del ejército de los muertos (que tenían una promesa por cumplir hecha al rey Isildur). Con esta espada, Aragorn, Legolas y Gimli abandonan al resto del ejército de Rohan y se adentran en una caverna en donde mora el ejército de los muertos. (En el libro de Tolkien al entrar a la caverna encuentran el cuerpo de Baldor hijo de Brego, segundo rey de Rohan). Estos fantasmas habían prometido ayuda a Isildur pero no se la brindaron, por lo que tras su victoria sobre Sauron los maldijo para que, aún después de muertos, no tuvieran paz. Solo si un día pagaban su deuda podrían hacerlo. Aragorn reclamó su ayuda, prometiendo como Rey de Gondor que daría su deuda por cumplida.',
            'Gollum, por su parte, después de haber dicho a Frodo que Sam quería quedarse con el Anillo, para lo que le pediría tomarlo en algún momento, tomó el pan que quedaba, dejó migas en las ropas de Sam y lo inculpó de haberse comido todo. Mientras Sam golpea repetidamente a Gollum, Frodo sufre una descompensación y Sam, al verlo se ofrece ayudarlo con el Anillo, así Gollum logra hacer que Frodo desconfíe de Sam y lo aparte de su viaje, justo cuando lo hizo entrar en el paso de Cirith-Ungol y al antro de Ella-Laraña. Aun así, logró liberarse y atacar a Gollum. Gollum aseguró ser inocente, que el Anillo lo obligaba a hacer lo que hizo, y Frodo le dijo entonces finalmente para qué iba a Mordor: para destruirlo. Gollum volvió a atacar, pero cayó por un barranco. Ella-Laraña atrapó a Frodo luego de eso, pero fue ahuyentada por Sam. Sam creyó que Frodo estaba muerto por el veneno que le inyectaron y le quitó el anillo para continuar la misión, pero entonces llegaron unos orcos. Sam se escondió, y los orcos encontraron y se llevaron el cuerpo de Frodo, que comentaron que no estaba muerto sino solo inconsciente por varias horas.debido a un conflicto entre los orcos por la cota de malla de mithril de Frodo, estos empezaron a matarse mutuamente. Sam se infiltró en su fortaleza y lo liberó, Frodo creyó que el anillo había sido tomado por los orcos, hasta que Sam le mostró el anillo, ante la negativa de Sam a darle el anillo por el daño que le causaba a Frodo, Frodo le explicó que la misión solo la podía cumplir él ya que podría llegar a matar a Sam. Tras esto continuaron su viaje, disfrazados de orcos para pasar inadvertidos.',
            'Denethor envió a su hijo Faramir en una misión destinada al fracaso porque le odiaba profundamente y le culpaba por la muerte de su hermano, para que recupere un bastión de Minas Tirith Osgiliath, conquistado previamente por los orcos. Faramir aceptó esa misión suicida solo por su afán de demostrarle a su padre que él también era un guerrero leal y competente, y dolido por la preferencia abierta que su padre siempre tuvo por Boromir. Solo Faramir logra regresar, pero mal herido y Denethor al ver a su hijo herido por varias flechas enloqueció, creyéndolo muerto. Mientras el grueso de las fuerzas de Mordor avanzaban sobre la ciudad, Denethor (olvidando defender Minas Tirith) fue junto a su hijo a quemarse vivo en una pira. Más tarde, Pippin le informa a Gandalf lo que va a hacer Denethor y apresuradamente va al palacio a salvar a Faramir. Gandalf logra retirar de la hoguera a Faramir, que aún estaba vivo, pero Denethor se incineró, cayendo al vacío desde la ciudadela.',
            'Por otro lado, las huestes de Mordor inician el asedio a la ciudad blanca. Gandalf se las arregló para organizar a las tropas de Gondor para la defensa a la espera de que llegue Théoden y sus jinetes, a pesar de que sea tarde. Durante todo un día los hombres de Gondor mantienen sus posiciones frente a la sombra gracias a su coraje y valor demostrado contra Mordor durante muchos enfrentamientos anteriores, lo que ocasiona bajas importantes en el ejército de Sauron. Sin embargo, debido a su gran número las fuerzas de Mordor apenas si podían ser contenidas, y con el gran ariete Grond tiraron abajo las puertas de la ciudad, entrando en Minas Tirith y obligando a los soldados de Gondor a retroceder al segundo nivel. Con estos sucesos y a pesar de la gran resistencia ofrecida por Gondor en cada calle, cada casa, luchando cada hombre hasta el último aliento, creyendo perdida la esperanza de sobrevivir y cuando ya la victoria de Sauron parecía cercana; en la versión extendida Gandalf y el Señor de los Nazgûl se enfrentan y justo cuando parece que Gandalf morirá aparecen en el horizonte los jinetes de Rohan, que volvieron a emparejar la situación gracias a su poderosa carga de caballería y hace retroceder a los orcos. Ante esto Mordor trajo poderosos refuerzos: un ejército de sureños (Haradrim) con olifantes (criaturas similares a elefantes, solo que mucho más grandes y sobre los cuales se construían grandes torres donde iban arqueros), ante esto el Rey de Rohan ordena que su ejército se forme para volver a cargar contra los sureños y con mucho esfuerzo los hombres de Rohan se libraron de algunos de ellos y mostraron gran resistencia a pesar de las bajas sufridas.',
            'La batalla parecía empezarse a perder, pero Théoden es herido mortalmente por el Rey Brujo, quien le ordenó a su bestia alada que se diera un festín con la carne del rey caído. Éowyn apareció para defenderlo y fue herida también por el espectro, el cual le recordó que ningún hombre era capaz de matarlo. En ese momento Merry apareció por detrás y le clavó su puñal en la pantorrilla; Éowyn se quitó el casco y reveló que no era un hombre sino una mujer, acto seguido le atravesó la cabeza invisible con su espada. El Rey Brujo finalmente desapareció, vencido no por un hombre sino por una mujer y un hobbit.',
            'Entonces aparecieron también varios barcos de los Corsarios de Umbar que Mordor esperaba, para atracar en los muelles de Osgilliath, pero para sorpresa de los orcos, de esos barcos bajaron Aragorn, Legolas y Gimli, que los habían tomado al abordaje. Con ellos venía el ejército de los muertos, que limpió los campos de Pelennor por completo: todas las clases de criaturas que Mordor había llevado a la guerra eran pulverizadas en segundos.',
            'Al terminar la batalla, el rey de los muertos reclamó a Aragorn cumplir su promesa de liberarlos. Gimli aconsejó no hacerlo, Mordor aún era un peligro y ellos eran muy útiles, pero Aragorn cumplió su promesa y consideró pagada su deuda. Los espectros desaparecieron.',
            'Gandalf aseguró que Sauron pronto recuperaría el Anillo y que resistir los ataques era inútil, ya que Mordor era mucho más poderoso y finalmente prevalecería. Su única esperanza era que Frodo tuviera éxito en destruir el Anillo, entonces Aragorn aconseja que reúnan a los hombres y marchen al Puerta Negra pero Éomer dice que no vencerán a Sauron. Sin embargo se preparan para que el ejército mantenga la atención de Sauron enfocada sobre ellos, y distraído de la presencia de Frodo y el Anillo en su propio territorio. Todos los supervivientes marcharon a la Puerta Negra, donde Aragorn exigió a Sauron que se rindiera, pero en lugar de eso las puertas se abrieron y por ella apareció el ejército del Señor Oscuro, y un mar de enemigos los rodeó.',
            'Desafiando a Sauron por última vez, los hombres del Oeste cargaron liderados por Aragorn contra los ejércitos de Sauron. Durante un tiempo mantuvieron su posición, pero el número de enemigos no parecía agotarse y las fuerzas de los hombres empezaban a decaer.',
            'Frodo y Sam llegaron finalmente al Monte del Destino, donde Gollum reaparece para recuperar el anillo. Pero, una vez junto al borde por donde Frodo podría tirar el anillo al fuego y destruirlo, finalmente sucumbe ante su poder y lo reclama para sí mismo. Gollum entró entonces y, aunque Frodo era invisible, se lo tiró encima y le arranca el dedo para quitarle el anillo. Entre ambos se lo disputaron al borde del abismo, y cayeron por él. Frodo se pudo sostener del borde, pero Gollum y el Anillo cayeron a las llamas y fueron destruidos. Justo en ese mismo momento, cuando el fin de los hombres parecía inevitable, la torre de Barad-dûr se vino abajo, el Gran Ojo explotó, Mordor se hundió en el suelo y todos los orcos huyeron o murieron.',
            'Gandalf rescató a Frodo y Sam de Orodruin (Monte del Destino) montando en el lomo de Gwaihir, el Señor de los Vientos, y los hobbits recibieron honores en Gondor durante la coronación de Aragorn como rey por parte de todos sus habitantes y también de Rohan, pues gracias a ellos su mundo se salvó y tenían una oportunidad de empezar a vivir al fin en paz. Luego volvieron a la Comarca, donde Sam se casó con Rosita. Frodo escribió sus memorias, dejándole a Sam el final del libro; finalmente se embarcó a las Tierras Imperecederas junto a Bilbo, Gandalf, Elrond, Galadriel y los elfos restantes. La película acaba con la vuelta de Sam a su casa, donde lo esperan su hija, Rosita y su pequeño bebé, tras despedir a sus amigos en los Puertos Grises. Sam dice: "Bueno. Estoy de vuelta", (palabras con las que también terminaba la novela), entran juntos en casa, y cierra la puerta.'
        ],
        'Producción': [
            '<h2>Guion</h2>',
            'El guion de El retorno del Rey, al igual que los de la primera y la segunda entregas de la trilogía, fue escrito por Philippa Boyens, Peter Jackson y su esposa, Fran Walsh. En el guion original, la escena inicial era un sueño en el que la cámara salía de la puerta de los Senderos de los Muertos, recorría Rohan hasta el castillo de Meduseld y, en ese momento, el personaje de Aragorn se despertaba de repente. La escena que finalmente la sustituyó y en la que se muestra un flashback del descubrimiento del Anillo por parte de Déagol y Sméagol iba a ser incluida en Las dos torres, junto cuando Frodo le recuerda a Gollum su verdadero nombre en la Ciénaga de los Muertos. Los guionistas consideraron que esta escena era más apropiada para comenzar El retorno del Rey que la del sueño de Aragorn, ya que según sus palabras le «aporta unidad» a la película al mostrar en el inicio el origen del Anillo y en el final su destrucción. Por idea de Fran Walsh, el flashback fue ampliado para mostrar el deterioro de Sméagol con el paso de los años debido a la posesión del Anillo.',
            'La escena del banquete en el castillo de Meduseld no aparecía en el guion, pero fue incorporada tiempo después debido a que algunos hilos argumentales no comenzaban de forma clara, como las dudas del rey Théoden sobre su capacidad para liderar o la relación entre Aragorn y Éowyn.',
            'Desde el principio, Jackson descartó incluir en Las dos torres las escenas de Ella-Laraña para evitar que coincidieran con la batalla del Abismo de Helm y el clímax de esta se rompiera. Además, de esta forma conseguían seguir un orden cronológico que J. R. R. Tolkien no hizo en la novela, ya que los hechos ocurridos en el antro de Ella-Laraña coinciden en el tiempo con el asedio de Minas Tirith. Sin embargo, esta reestructuración cronológica hizo que algunas escenas perdieran tensión con respecto al libro, por ejemplo la acontecida en la Puerta Negra de Mordor con la Boca de Sauron, ya que mientras en la novela los lectores no saben si Frodo está vivo o muerto, en la película sí.',
            'En la primera versión de la escena acontecida en el Monte del Destino, Frodo empujaba a Gollum y este se caía a la lava junto con el Anillo; sin embargo, tras verla rodada, la escena no convenció a los guionistas y finalmente hicieron que los dos personajes forcejearan por el Anillo (como espejo de la escena inicial de la película entre Sméagol y Déagol) y cayeran accidentalmente.',
            'El Saneamiento de la Comarca fue descartado pronto por los guionistas, ya que la trama de la trilogía se centraba en la destrucción del Anillo y tras eso solo querían finalizar la película. A pesar de ello, intentaron rendirle homenaje en La Comunidad del Anillo cuando Frodo ve en el Espejo de Galadriel la Comarca destruida y a los hobbits siendo apresados por orcos. La muerte del mago Saruman, que en la novela ocurre durante el Saneamiento de la Comarca, fue trasladada a lo alto de la torre de Orthanc e iba a ser mostrada al final de Las dos torres, pero finalmente cambiaron el guion para que apareciera al principio de El retorno del Rey con el fin de no romper el clímax final de la segunda entrega. La escena fue omitida de nuevo en la versión estrenada en cines para reducir la duración de la película y, aunque fue incluida en la versión extendida publicada en DVD, esto provocó que el actor Christopher Lee mostrara abiertamente su molestia hacia Jackson.',
            'En un principio, los guionistas escribieron escenas finales para todos los miembros de la Comunidad del Anillo, e incluso fueron rodadas, pero finalmente solo incluyeron la de Aragorn y se centraron en el deterioramiento de Frodo a causa del viaje.',
            '<h2>Rodaje</h2>',
            'Las tres entregas de la trilogía fueron rodadas al mismo tiempo en Nueva Zelanda, en un período de entre catorce y quince meses desde finales de 1999 hasta el fin de 2000. En plan inicial de Peter Jackson era rodar en primer lugar La Comunidad del Anillo, pero debido a las inundaciones que se produjeron en Queenstown el equipo de rodaje no pudo filmar escenas en exteriores; como resultado de ello, se planeó que Elijah Wood y Sean Astin comenzaran a rodar las escenas que transcurren en las escaleras de Cirith Ungol en El retorno del Rey. Weta Workshop diseñó una maqueta de las escaleras para los planos abiertos, pero para las escenas con diálogo se construyó un escenario en la pista de squash de un hotel y el director de animación Randy Cook hizo el papel de Gollum, ya que Andy Serkis aún no había sido contratado. Las escenas iban a ser filmadas el 24 y 25 de noviembre de 1999, pero tras la primera jornada de rodaje salió el sol y Jackson decidió continuar rodando los exteriores de La Comunidad del Anillo, por lo que firmó un contrato con el hotel para poder mantener el escenario montado hasta que volvieran a filmar en él. El equipo de rodaje no volvería allí hasta un año después, el 30 de noviembre de 2000.',
            '<h2>Diseño</h2>',
            'La Tierra Media imaginada por Jackson fue diseñada principalmente por Alan Lee y John Howe, dos de los principales ilustradores de J. R. R. Tolkien, y creada por la empresa Weta Workshop, que se hizo cargo de las armas, armaduras, miniaturas, prótesis y criaturas de toda la trilogía, así como por el Departamento de Arte que construyó los platós. Richard Taylor dirigió Weta, mientras que Grant Major y Dan Hennah organizaron la planificación y los edificios respectivamente.',
            'La ciudad de Minas Tirith, vista brevemente en las películas previas, se ve completamente en esta tercera, y con ello la civilización de Gondor. El enorme escenario se construyó en Dry Creek Quarry, en las afueras de Wellington, en el plató del Abismo de Helm. Este plató se convirtió en la segunda puerta de Minas Tirith, mientras que el exterior del Abismo de Helm sirvió para la escena donde Gandalf se enfrenta al Rey Brujo. Las nuevas estructuras incluían una puerta de ocho metros en dos versiones, una rota y otra intacta, con una apertura manual y un mecanismo de cierre; sus grabados se inspiraron en el Bautismo de San Juan. Había también cuatro niveles de calles con motivos heráldicos en todas las casas, inspirados en Siena. La ciudadela fue construida en el exterior de la que era el backlot de los estudios Stone Street, utilizando una perspectiva forzada. En ella se emplazó el marchito Árbol Blanco de Gondor, hecho de poliestireno por Brian Massey con ramas reales e inspirado en los viejas y nudosos olivos libaneses. El interior fue construido dentro de una vieja fábrica de tres niveles en Wellington y sus colores estuvieron influidos por la Capilla Palatina de Aquisgrán, con un trono para Denethor cavado en la piedra y estatuas de poliestireno de los antiguos Reyes de Gondor.',
            'La armadura gondoriana fue diseñada para representar una evolución de los númenóreanos desde el prólogo de la primera película, con un simplificado motivo de pájaros marinos. El siglo xvi italiano y alemán sirvieron de inspiración, mientras que los civiles vestían trajes en plata y negro, diseñados por Ngila Dickson continuando el estilo antiguo y medieval mediterráneo.',
            'Minas Morgul, la escalera, la guarida del Ella-Laraña y la torre de Cirith Ungol fueron diseñados por Howe. El diseño de Minas Morgul fue inspirado por una experiencia del artista con una muela del juicio, mientras que Cirith Ungol se basó en los dibujos de Tolkien, aunque rediseñado por Richard Taylor con un estilo más inglés. Los Puertos Grises estuvieron inspirados en los cuadros de J. M. W. Turner.',
            'La tercera película introduce a la araña gigante Ella-Laraña. El personaje fue diseñado en 1999, basando su cuerpo en una Porrhothele antipodiana y se añadió a su cabeza numerosos bultos que fueron seleccionados por los hijos de Peter Jackson de entre varias opciones. Los muertos de El Sagrario tienen una influencia celta, con acabados rectilíneos y simétricos para reflejar su estado mórbido, mientras que su ciudad subterránea tiene un aire a Petra. Los haradrim inicialmente estaban inspirados por la cultura africana, pero a Philippa Boyens le preocupaba que esto resultara ofensivo y el aspecto de la raza acabó siendo influido por los kiribati, con una armadura trenzada de bambú, y por los aztecas, debido al uso de joyas.',
            '<h2> Banda sonora </h2>',
            'La banda sonora original de El retorno del Rey fue lanzada el 25 de noviembre de 2003. Su tema final «Into the West» fue interpretado por Annie Lennox y ganó el Óscar a la mejor canción original en 2004.'
        ],
        'Premios': [
            '<h2>Premios Óscar</h2>',
            'La película fue nominada a once premios Óscar en la 76.ª edición de los premios, incluyendo mejor película, mejor director, mejor guion adaptado, mejor actor de reparto (Sean Astin), mejor actriz de reparto (Miranda Otto), mejor dirección artística, mejor vestuario, mejor maquillaje, mejor montaje, mejor sonido y mejor banda sonora. Ganó en todas las categorías en las que fue nominada, igualando el récord de Titanic y Ben-Hur de once premios Óscar, incluyendo el de mejor película y mejor director. La película también ganó el premio a la mejor película en los premios BAFTA, los premios del Sindicato de Actores y los premios del Círculo de Críticos de Cine de Nueva York, entre otros.',
            '<h2>Premios Globo de Oro</h2>',
            'La película fue nominada a cuatro premios Globo de Oro en la 61.ª edición de los premios, incluyendo mejor película - drama, mejor director, mejor guion y mejor banda sonora. Ganó en todas las categorías en las que fue nominada, incluyendo el de mejor película - drama y mejor director.',
            '<h2>Premios BAFTA</h2>',
            'La película fue nominada a doce premios BAFTA en la 57.ª edición de los premios, incluyendo mejor película, mejor director, mejor guion adaptado, mejor actor de reparto (Sean Astin), mejor actriz de reparto (Miranda Otto), mejor dirección artística, mejor vestuario, mejor maquillaje y peluquería, mejor sonido, mejor montaje, mejor banda sonora y mejor fotografía. Ganó en todas las categorías en las que fue nominada, incluyendo el de mejor película y mejor director.',
            '<h2>Premios del Sindicato de Actores</h2>',
            'La película fue nominada a once premios del Sindicato de Actores en la 10.ª edición de los premios, incluyendo mejor reparto, mejor actor de reparto (Sean Astin), mejor actriz de reparto (Miranda Otto), mejor reparto de dobles de riesgo, mejor reparto de dobles de riesgo en una película de acción, mejor reparto de dobles de riesgo en una película de fantasía, mejor reparto de dobles de riesgo en una película de aventuras, mejor reparto de dobles de riesgo en una película de drama, mejor reparto de dobles de riesgo en una película de ciencia ficción, mejor reparto de dobles de riesgo en una película de terror y mejor reparto de dobles de riesgo en una película de televisión. Ganó en todas las categorías en las que fue nominada, incluyendo el de mejor reparto.',
            '<h2>Premios del Círculo de Críticos de Cine de Nueva York</h2>',
            'La película fue nominada a cuatro premios del Círculo de Críticos de Cine de Nueva York en la 69.ª edición de los premios, incluyendo mejor película, mejor director, mejor guion y mejor banda sonora. Ganó en todas las categorías en las que fue nominada, incluyendo el de mejor película y mejor director.',
            '<h2>Premios Saturn</h2>',
            'La película fue nominada a diez premios Saturn en la 30.ª edición de los premios, incluyendo mejor película de fantasía, mejor director, mejor guion, mejor actor (Viggo Mortensen), mejor actor de reparto (Sean Astin), mejor actriz de reparto (Miranda Otto), mejor vestuario, mejor maquillaje, mejor banda sonora y mejor montaje. Ganó en todas las categorías en las que fue nominada, incluyendo el de mejor película de fantasía y mejor director.',
            '<h2>Premios Grammy</h2>',
            'La banda sonora original de El retorno del Rey fue nominada a cuatro premios Grammy en la 47.ª edición de los premios, incluyendo mejor banda sonora, mejor composición instrumental, mejor álbum de banda sonora y mejor álbum de banda sonora para medios visuales. Ganó en todas las categorías en las que fue nominada, incluyendo el de mejor banda sonora y mejor álbum de banda sonora para medios visuales.',
            '<h2>Premios Hugo</h2>',
            'La película fue nominada a dos premios Hugo en la 62.ª edición de los premios, incluyendo mejor presentación dramática - forma larga y mejor representación dramática - forma corta. Ganó en la categoría de mejor presentación dramática - forma larga.',
        ]
    },

}